"""
Legend MiuiSystemUI MTCR patch — modified class.

Target APK   : MiuiSystemUI.apk
Target class : com/android/wm/shell/multitasking/miuifreeform/miuibubbles/settings/MiuiBubbleSettings.smali
Patches      : 1
"""
from __future__ import annotations

TARGET_APK           = 'MiuiSystemUI.apk'
TARGET_CLASS         = 'com/android/wm/shell/multitasking/miuifreeform/miuibubbles/settings/MiuiBubbleSettings.smali'
CLASS_FALLBACK_NAMES = ['MiuiBubbleSettings.smali']
CLASS_ANCHORS        = ['invoke-static {p0}, Lcom/android/wm/shell/multitasking/miuifreeform/miuibubbles/settings/MiuiBubbleSettings;->lambda$refreshActiveBubble$0(Lcom/android/wm/shell/multitasking/miuifreeform/miuibubbles/MiuiBubble;)Z', 'invoke-static {p0, p1, p2}, Lcom/android/wm/shell/multitasking/miuifreeform/miuibubbles/settings/MiuiBubbleSettings;->lambda$removeActiveBubble$1(Ljava/lang/String;ILcom/android/wm/shell/multitasking/miuifreeform/miuibubbles/MiuiBubble;)Z', 'invoke-direct {v0, v1}, Ljava/util/HashSet;-><init>(I)V', 'sput-object v0, Lcom/android/wm/shell/multitasking/miuifreeform/miuibubbles/settings/MiuiBubbleSettings;->mActiveBubbles:Ljava/util/HashSet;', 'invoke-direct {v0}, Landroid/util/ArrayMap;-><init>()V']

PATCHES = [
    {
        'id':             'p0000_getDefaultBubbles',
        'type':           'method_replace',
        'method':         '.method private static getDefaultBubbles(Landroid/content/Context;)Landroid/util/ArrayMap;',
        'method_name':    'getDefaultBubbles',
        'method_anchors': ['invoke-direct {v1}, Landroid/util/ArrayMap;-><init>()V', 'invoke-static {p0}, Landroid/util/MiuiMultiWindowUtils;->getFreeformSuggestionList(Landroid/content/Context;)Ljava/util/ArrayList;', 'invoke-virtual {v2, v4}, Ljava/util/ArrayList;->toArray([Ljava/lang/Object;)[Ljava/lang/Object;'],
        'search':         '.method private static getDefaultBubbles(Landroid/content/Context;)Landroid/util/ArrayMap;\n    .registers 8\n    .annotation system Ldalvik/annotation/Signature;\n        value = {\n            "(",\n            "Landroid/content/Context;",\n            ")",\n            "Landroid/util/ArrayMap<",\n            "Ljava/lang/String;",\n            "Lmiui/app/MiuiBubbleApp;",\n            ">;"\n        }\n    .end annotation\n\n    const/4 v0, 0x1\n\n    new-instance v1, Landroid/util/ArrayMap;\n\n    invoke-direct {v1}, Landroid/util/ArrayMap;-><init>()V\n\n    invoke-virtual {p0}, Landroid/content/Context;->getResources()Landroid/content/res/Resources;\n\n    move-result-object p0\n\n    const v2, 0x7f03008f\n\n    invoke-virtual {p0, v2}, Landroid/content/res/Resources;->getStringArray(I)[Ljava/lang/String;\n\n    move-result-object p0\n\n    array-length v2, p0\n\n    const/4 v3, 0x0\n\n    :goto_0\n    if-ge v3, v2, :cond_0\n\n    aget-object v4, p0, v3\n\n    new-instance v5, Lmiui/app/MiuiBubbleApp;\n\n    sget v6, Lcom/android/wm/shell/multitasking/miuifreeform/miuibubbles/settings/MiuiBubbleSettings;->mCurrentUserId:I\n\n    invoke-direct {v5, v4, v6}, Lmiui/app/MiuiBubbleApp;-><init>(Ljava/lang/String;I)V\n\n    invoke-virtual {v5, v0}, Lmiui/app/MiuiBubbleApp;->setChecked(Z)Lmiui/app/MiuiBubbleApp;\n\n    invoke-virtual {v1, v4, v5}, Landroid/util/ArrayMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;\n\n    add-int/2addr v3, v0\n\n    goto :goto_0\n\n    :cond_0\n    return-object v1\n.end method\n',
        'replacement':    '.method private static getDefaultBubbles(Landroid/content/Context;)Landroid/util/ArrayMap;\n    .registers 8\n    .annotation system Ldalvik/annotation/Signature;\n        value = {\n            "(",\n            "Landroid/content/Context;",\n            ")",\n            "Landroid/util/ArrayMap<",\n            "Ljava/lang/String;",\n            "Lmiui/app/MiuiBubbleApp;",\n            ">;"\n        }\n    .end annotation\n\n    const/4 v0, 0x1\n\n    new-instance v1, Landroid/util/ArrayMap;\n\n    invoke-direct {v1}, Landroid/util/ArrayMap;-><init>()V\n\n    invoke-static {p0}, Landroid/util/MiuiMultiWindowUtils;->getFreeformSuggestionList(Landroid/content/Context;)Ljava/util/ArrayList;\n\n    move-result-object v2\n\n    const/4 v3, 0x0\n\n    if-eqz v2, :cond_0\n\n    new-array v4, v3, [Ljava/lang/String;\n\n    invoke-virtual {v2, v4}, Ljava/util/ArrayList;->toArray([Ljava/lang/Object;)[Ljava/lang/Object;\n\n    move-result-object p0\n\n    check-cast p0, [Ljava/lang/String;\n\n    goto :goto_0\n\n    :cond_0\n    invoke-virtual {p0}, Landroid/content/Context;->getResources()Landroid/content/res/Resources;\n\n    move-result-object p0\n\n    const v2, 0x7f03008f\n\n    invoke-virtual {p0, v2}, Landroid/content/res/Resources;->getStringArray(I)[Ljava/lang/String;\n\n    move-result-object p0\n\n    :goto_0\n    array-length v2, p0\n\n    :goto_1\n    if-ge v3, v2, :cond_1\n\n    aget-object v4, p0, v3\n\n    new-instance v5, Lmiui/app/MiuiBubbleApp;\n\n    sget v6, Lcom/android/wm/shell/multitasking/miuifreeform/miuibubbles/settings/MiuiBubbleSettings;->mCurrentUserId:I\n\n    invoke-direct {v5, v4, v6}, Lmiui/app/MiuiBubbleApp;-><init>(Ljava/lang/String;I)V\n\n    invoke-virtual {v5, v0}, Lmiui/app/MiuiBubbleApp;->setChecked(Z)Lmiui/app/MiuiBubbleApp;\n\n    invoke-virtual {v1, v4, v5}, Landroid/util/ArrayMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;\n\n    add-int/2addr v3, v0\n\n    goto :goto_1\n\n    :cond_1\n    return-object v1\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
]
