"""
Legend MiuiSystemUI MTCR patch — modified class.

Target APK   : MiuiSystemUI.apk
Target class : com/android/systemui/statusbar/views/MiuiClock.smali
Patches      : 13
"""
from __future__ import annotations

TARGET_APK           = 'MiuiSystemUI.apk'
TARGET_CLASS         = 'com/android/systemui/statusbar/views/MiuiClock.smali'
CLASS_FALLBACK_NAMES = ['MiuiClock.smali']
CLASS_ANCHORS        = ['invoke-direct {p0, p1, p2, v0}, Lcom/android/systemui/statusbar/views/MiuiClock;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V', 'invoke-direct {p0, p1, p2, p3}, Landroid/widget/TextView;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V', 'iput p3, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mPolicyVisibility:I', 'iput p3, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mMultiTaskVisibility:I', 'iput p3, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->blurRadius:I']

PATCHES = [
    {
        'id':             'p0000_startSecondsTicker',
        'type':           'method_add',
        'method':         '.method private startSecondsTicker()V',
        'method_name':    'startSecondsTicker',
        'method_anchors': ['iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z', 'invoke-virtual {p0}, Landroid/widget/TextView;->getVisibility()I', 'invoke-virtual {p0, p0}, Landroid/widget/TextView;->removeCallbacks(Ljava/lang/Runnable;)Z'],
        'search':         None,
        'replacement':    '.method private startSecondsTicker()V\n    .registers 8\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z\n\n    if-eqz v0, :cond_0\n\n    invoke-virtual {p0}, Landroid/widget/TextView;->getVisibility()I\n\n    move-result v0\n\n    if-nez v0, :cond_0\n\n    invoke-virtual {p0, p0}, Landroid/widget/TextView;->removeCallbacks(Ljava/lang/Runnable;)Z\n\n    invoke-static {}, Ljava/lang/System;->currentTimeMillis()J\n\n    move-result-wide v0\n\n    const-wide/16 v2, 0x3e8\n\n    rem-long/2addr v0, v2\n\n    sub-long v0, v2, v0\n\n    invoke-virtual {p0, p0, v0, v1}, Landroid/widget/TextView;->postDelayed(Ljava/lang/Runnable;J)Z\n\n    :cond_0\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0001_stopSecondsTicker',
        'type':           'method_add',
        'method':         '.method private stopSecondsTicker()V',
        'method_name':    'stopSecondsTicker',
        'method_anchors': ['invoke-virtual {p0, p0}, Landroid/widget/TextView;->removeCallbacks(Ljava/lang/Runnable;)Z'],
        'search':         None,
        'replacement':    '.method private stopSecondsTicker()V\n    .registers 2\n\n    invoke-virtual {p0, p0}, Landroid/widget/TextView;->removeCallbacks(Ljava/lang/Runnable;)Z\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0002_hasOverlappingRendering',
        'type':           'method_add',
        'method':         '.method public hasOverlappingRendering()Z',
        'method_name':    'hasOverlappingRendering',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.method public hasOverlappingRendering()Z\n    .registers 1\n\n    const/4 p0, 0x0\n\n    return p0\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0003_onAttachedToWindow',
        'type':           'method_add',
        'method':         '.method public onAttachedToWindow()V',
        'method_name':    'onAttachedToWindow',
        'method_anchors': ['invoke-super {p0}, Landroid/widget/TextView;->onAttachedToWindow()V', 'iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z', 'iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z'],
        'search':         None,
        'replacement':    '.method public onAttachedToWindow()V\n    .registers 2\n\n    invoke-super {p0}, Landroid/widget/TextView;->onAttachedToWindow()V\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z\n\n    if-nez v0, :cond_0\n\n    const/4 v0, 0x1\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mMiuiStatusBarClockController:Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;\n\n    iget-object v0, v0, Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;->mClockListeners:Ljava/util/ArrayList;\n\n    invoke-virtual {v0, p0}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/MiuiClock;->updateTime()V\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAutoDark:Z\n\n    if-eqz v0, :cond_0\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mShowDark:Z\n\n    if-eqz v0, :cond_0\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mMiuiStatusBarClockController:Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;\n\n    iget-object v0, v0, Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;->mDarkIconDispatcher:Lcom/android/systemui/plugins/DarkIconDispatcher;\n\n    invoke-interface {v0, p0}, Lcom/android/systemui/plugins/DarkIconDispatcher;->addDarkReceiver(Lcom/android/systemui/plugins/DarkIconDispatcher$DarkReceiver;)V\n\n    :cond_0\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/MiuiClock;->updateClockVisibility()V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0004_onDarkChanged',
        'type':           'method_add',
        'method':         '.method public onDarkChanged(Ljava/util/ArrayList;FI)V',
        'method_name':    'onDarkChanged',
        'method_anchors': ['iput-object p1, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAreas:Ljava/util/ArrayList;', 'iput p2, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mDarkIntensity:F', 'iput p3, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mTint:I'],
        'search':         None,
        'replacement':    '.method public onDarkChanged(Ljava/util/ArrayList;FI)V\n    .registers 11\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAreas:Ljava/util/ArrayList;\n\n    iput p2, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mDarkIntensity:F\n\n    iput p3, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mTint:I\n\n    iget v4, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mLightColor:I\n\n    iget v5, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mDarkColor:I\n\n    iget-boolean v6, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mUseTint:Z\n\n    move-object v0, p0\n\n    move-object v1, p1\n\n    move v2, p2\n\n    move v3, p3\n\n    invoke-virtual/range {v0 .. v6}, Lcom/android/systemui/statusbar/views/MiuiClock;->updateLightDarkTint$2(Ljava/util/ArrayList;FIIIZ)V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0005_onDetachedFromWindow',
        'type':           'method_add',
        'method':         '.method public onDetachedFromWindow()V',
        'method_name':    'onDetachedFromWindow',
        'method_anchors': ['invoke-super {p0}, Landroid/widget/TextView;->onDetachedFromWindow()V', 'invoke-direct {p0}, Lcom/android/systemui/statusbar/views/MiuiClock;->stopSecondsTicker()V', 'iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z'],
        'search':         None,
        'replacement':    '.method public onDetachedFromWindow()V\n    .registers 2\n\n    invoke-super {p0}, Landroid/widget/TextView;->onDetachedFromWindow()V\n\n    invoke-direct {p0}, Lcom/android/systemui/statusbar/views/MiuiClock;->stopSecondsTicker()V\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z\n\n    if-eqz v0, :cond_0\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mMiuiStatusBarClockController:Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;\n\n    iget-object v0, v0, Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;->mClockListeners:Ljava/util/ArrayList;\n\n    invoke-virtual {v0, p0}, Ljava/util/ArrayList;->remove(Ljava/lang/Object;)Z\n\n    const/4 v0, 0x0\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAutoDark:Z\n\n    if-eqz v0, :cond_0\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mShowDark:Z\n\n    if-eqz v0, :cond_0\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mMiuiStatusBarClockController:Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;\n\n    iget-object v0, v0, Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;->mDarkIconDispatcher:Lcom/android/systemui/plugins/DarkIconDispatcher;\n\n    invoke-interface {v0, p0}, Lcom/android/systemui/plugins/DarkIconDispatcher;->removeDarkReceiver(Lcom/android/systemui/plugins/DarkIconDispatcher$DarkReceiver;)V\n\n    :cond_0\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0006_onLightDarkTintChanged',
        'type':           'method_add',
        'method':         '.method public onLightDarkTintChanged(IIZ)V',
        'method_name':    'onLightDarkTintChanged',
        'method_anchors': ['iput p1, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mLightColor:I', 'iput p2, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mDarkColor:I', 'iput-boolean p3, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mUseTint:Z'],
        'search':         None,
        'replacement':    '.method public onLightDarkTintChanged(IIZ)V\n    .registers 11\n\n    iput p1, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mLightColor:I\n\n    iput p2, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mDarkColor:I\n\n    iput-boolean p3, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mUseTint:Z\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAreas:Ljava/util/ArrayList;\n\n    iget v2, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mDarkIntensity:F\n\n    iget v3, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mTint:I\n\n    move-object v0, p0\n\n    move v4, p1\n\n    move v5, p2\n\n    move v6, p3\n\n    invoke-virtual/range {v0 .. v6}, Lcom/android/systemui/statusbar/views/MiuiClock;->updateLightDarkTint$2(Ljava/util/ArrayList;FIIIZ)V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0007_run',
        'type':           'method_add',
        'method':         '.method public run()V',
        'method_name':    'run',
        'method_anchors': ['iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z', 'invoke-virtual {p0}, Landroid/widget/TextView;->getVisibility()I', 'invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/MiuiClock;->updateTime()V'],
        'search':         None,
        'replacement':    '.method public run()V\n    .registers 2\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAttached:Z\n\n    if-eqz v0, :cond_0\n\n    invoke-virtual {p0}, Landroid/widget/TextView;->getVisibility()I\n\n    move-result v0\n\n    if-nez v0, :cond_0\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/MiuiClock;->updateTime()V\n\n    invoke-direct {p0}, Lcom/android/systemui/statusbar/views/MiuiClock;->startSecondsTicker()V\n\n    :cond_0\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0008_updateClockVisibility',
        'type':           'method_add',
        'method':         '.method public updateClockVisibility()V',
        'method_name':    'updateClockVisibility',
        'method_anchors': ['iget v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mPolicyVisibility:I', 'iget v2, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mMultiTaskVisibility:I', 'invoke-virtual {p0, v0}, Landroid/widget/TextView;->setVisibility(I)V'],
        'search':         None,
        'replacement':    '.method public updateClockVisibility()V\n    .registers 4\n\n    iget v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mPolicyVisibility:I\n\n    const/16 v1, 0x8\n\n    if-eq v0, v1, :cond_3\n\n    iget v2, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mMultiTaskVisibility:I\n\n    if-ne v2, v1, :cond_0\n\n    goto :goto_1\n\n    :cond_0\n    const/4 v1, 0x4\n\n    if-eq v0, v1, :cond_2\n\n    if-ne v2, v1, :cond_1\n\n    goto :goto_0\n\n    :cond_1\n    const/4 v0, 0x0\n\n    invoke-virtual {p0, v0}, Landroid/widget/TextView;->setVisibility(I)V\n\n    invoke-direct {p0}, Lcom/android/systemui/statusbar/views/MiuiClock;->startSecondsTicker()V\n\n    return-void\n\n    :cond_2\n    :goto_0\n    invoke-virtual {p0, v1}, Landroid/widget/TextView;->setVisibility(I)V\n\n    invoke-direct {p0}, Lcom/android/systemui/statusbar/views/MiuiClock;->stopSecondsTicker()V\n\n    return-void\n\n    :cond_3\n    :goto_1\n    invoke-virtual {p0, v1}, Landroid/widget/TextView;->setVisibility(I)V\n\n    invoke-direct {p0}, Lcom/android/systemui/statusbar/views/MiuiClock;->stopSecondsTicker()V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0009_updateTime',
        'type':           'method_add',
        'method':         '.method public updateTime()V',
        'method_name':    'updateTime',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mMiuiStatusBarClockController:Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;', 'iget-object v0, v0, Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;->mCalendar:Lmiuix/pickerwidget/date/Calendar;', 'invoke-static {}, Ljava/lang/System;->currentTimeMillis()J'],
        'search':         None,
        'replacement':    '.method public updateTime()V\n    .registers 15\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mMiuiStatusBarClockController:Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;\n\n    iget-object v0, v0, Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;->mCalendar:Lmiuix/pickerwidget/date/Calendar;\n\n    if-nez v0, :cond_0\n\n    goto :goto_a\n\n    :cond_0\n    invoke-static {}, Ljava/lang/System;->currentTimeMillis()J\n\n    move-result-wide v11\n\n    invoke-virtual {v0, v11, v12}, Lmiuix/pickerwidget/date/Calendar;->setTimeInMillis(J)V\n\n    invoke-virtual {p0}, Landroid/widget/TextView;->getContext()Landroid/content/Context;\n\n    move-result-object v1\n\n    iget-object v2, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mMiuiStatusBarClockController:Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;\n\n    iget-boolean v2, v2, Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;->mIs24:Z\n\n    const/16 v3, 0x10\n\n    if-eqz v2, :cond_1\n\n    const/16 v2, 0x20\n\n    goto :goto_0\n\n    :cond_1\n    move v2, v3\n\n    :goto_0\n    iget v4, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mClockMode:I\n\n    const/4 v5, 0x2\n\n    const/4 v6, 0x0\n\n    if-ne v4, v5, :cond_4\n\n    if-ne v2, v3, :cond_2\n\n    const v2, 0x7f140e95\n\n    goto :goto_1\n\n    :cond_2\n    const v2, 0x7f140e94\n\n    :goto_1\n    invoke-virtual {v1, v2}, Landroid/content/Context;->getString(I)Ljava/lang/String;\n\n    move-result-object v2\n\n    const-string v2, "datastylest1"\n\n    invoke-static {v2}, Landroid/preference/SettingsMezoHelper;->getIntofSettings(Ljava/lang/String;)I\n\n    move-result v2\n\n    const/4 v10, 0x1\n\n    if-eq v2, v10, :cond_3\n\n    goto :goto_2\n\n    :cond_3\n    const-string v9, "H:mm"\n\n    const-string v2, "datast2"\n\n    invoke-static {v2, v9}, Landroid/preference/SettingsMezoHelper;->getStringofSettings(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;\n\n    move-result-object v2\n\n    goto :goto_3\n\n    :goto_2\n    const-string v2, "H:mm"\n\n    :goto_3\n    invoke-virtual {v0, v1, v2}, Lmiuix/pickerwidget/date/Calendar;->format(Landroid/content/Context;Ljava/lang/CharSequence;)Ljava/lang/String;\n\n    move-result-object v0\n\n    goto :goto_9\n\n    :cond_4\n    const/4 v5, 0x4\n\n    const v7, 0x7f140e92\n\n    if-ne v4, v5, :cond_6\n\n    invoke-virtual {v1, v7}, Landroid/content/Context;->getString(I)Ljava/lang/String;\n\n    move-result-object v2\n\n    const-string v2, "datastylest2"\n\n    invoke-static {v2}, Landroid/preference/SettingsMezoHelper;->getIntofSettings(Ljava/lang/String;)I\n\n    move-result v2\n\n    const/4 v10, 0x1\n\n    if-eq v2, v10, :cond_5\n\n    goto :goto_4\n\n    :cond_5\n    const-string v9, "EEEE d MMMM"\n\n    const-string v2, "datast3"\n\n    invoke-static {v2, v9}, Landroid/preference/SettingsMezoHelper;->getStringofSettings(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;\n\n    move-result-object v2\n\n    goto :goto_5\n\n    :goto_4\n    const-string v2, "EEEE d MMMM"\n\n    :goto_5\n    invoke-virtual {v0, v1, v2}, Lmiuix/pickerwidget/date/Calendar;->format(Landroid/content/Context;Ljava/lang/CharSequence;)Ljava/lang/String;\n\n    move-result-object v0\n\n    goto :goto_9\n\n    :cond_6\n    const/4 v5, 0x1\n\n    const v8, 0x7f140e93\n\n    if-ne v4, v5, :cond_8\n\n    if-ne v2, v3, :cond_7\n\n    move v7, v8\n\n    :cond_7\n    invoke-virtual {v1, v7}, Landroid/content/Context;->getString(I)Ljava/lang/String;\n\n    move-result-object v2\n\n    invoke-virtual {v0, v1, v2}, Lmiuix/pickerwidget/date/Calendar;->format(Landroid/content/Context;Ljava/lang/CharSequence;)Ljava/lang/String;\n\n    move-result-object v0\n\n    goto :goto_9\n\n    :cond_8\n    const/4 v5, 0x3\n\n    if-ne v4, v5, :cond_c\n\n    if-ne v2, v3, :cond_9\n\n    const v4, 0x7f140e98\n\n    goto :goto_6\n\n    :cond_9\n    const v4, 0x7f140e99\n\n    :goto_6\n    invoke-virtual {v1, v4}, Landroid/content/Context;->getString(I)Ljava/lang/String;\n\n    move-result-object v4\n\n    const-string v4, "datastylest3"\n\n    invoke-static {v4}, Landroid/preference/SettingsMezoHelper;->getIntofSettings(Ljava/lang/String;)I\n\n    move-result v4\n\n    const/4 v10, 0x1\n\n    if-eq v4, v10, :cond_a\n\n    goto :goto_7\n\n    :cond_a\n    const-string v9, "EEEE d MMMM"\n\n    const-string v4, "datast4"\n\n    invoke-static {v4, v9}, Landroid/preference/SettingsMezoHelper;->getStringofSettings(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;\n\n    move-result-object v4\n\n    goto :goto_8\n\n    :goto_7\n    const-string v4, "EEEE d MMMM"\n\n    :goto_8\n    invoke-virtual {v0, v1, v4}, Lmiuix/pickerwidget/date/Calendar;->format(Landroid/content/Context;Ljava/lang/CharSequence;)Ljava/lang/String;\n\n    move-result-object v4\n\n    if-ne v2, v3, :cond_b\n\n    move v7, v8\n\n    :cond_b\n    invoke-virtual {v1, v7}, Landroid/content/Context;->getString(I)Ljava/lang/String;\n\n    move-result-object v2\n\n    invoke-virtual {v0, v1, v2}, Lmiuix/pickerwidget/date/Calendar;->format(Landroid/content/Context;Ljava/lang/CharSequence;)Ljava/lang/String;\n\n    move-result-object v6\n\n    move-object v0, v4\n\n    goto :goto_9\n\n    :cond_c\n    iget v3, p0, Lcom/android/systemui/statusbar/views/MiuiClock;->mAmPmStyle:I\n\n    if-nez v3, :cond_d\n\n    invoke-virtual {v0}, Lmiuix/pickerwidget/date/Calendar;->getTimeInMillis()J\n\n    move-result-wide v3\n\n    or-int/lit8 v0, v2, 0xc\n\n    invoke-static {v1, v3, v4, v0}, Lmiuix/pickerwidget/date/DateUtils;->formatDateTime(Landroid/content/Context;JI)Ljava/lang/String;\n\n    move-result-object v0\n\n    goto :goto_9\n\n    :cond_d\n    invoke-virtual {v0}, Lmiuix/pickerwidget/date/Calendar;->getTimeInMillis()J\n\n    move-result-wide v3\n\n    or-int/lit8 v0, v2, 0x4c\n\n    invoke-static {v1, v3, v4, v0}, Lmiuix/pickerwidget/date/DateUtils;->formatDateTime(Landroid/content/Context;JI)Ljava/lang/String;\n\n    move-result-object v0\n\n    :goto_9\n    invoke-virtual {p0}, Landroid/widget/TextView;->getText()Ljava/lang/CharSequence;\n\n    move-result-object v1\n\n    invoke-static {v0, v1}, Landroid/text/TextUtils;->equals(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Z\n\n    move-result v1\n\n    if-nez v1, :cond_f\n\n    if-eqz v6, :cond_e\n\n    invoke-virtual {p0, v6}, Landroid/widget/TextView;->setContentDescription(Ljava/lang/CharSequence;)V\n\n    :cond_e\n    invoke-virtual {p0, v0}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V\n\n    invoke-virtual {p0}, Landroid/widget/TextView;->getParent()Landroid/view/ViewParent;\n\n    move-result-object v1\n\n    invoke-interface {v1}, Landroid/view/ViewParent;->getParent()Landroid/view/ViewParent;\n\n    move-result-object v1\n\n    instance-of v1, v1, Lcom/android/systemui/qs/MiuiNotificationHeaderView;\n\n    if-eqz v1, :cond_f\n\n    new-instance v1, Ljava/lang/StringBuilder;\n\n    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V\n\n    invoke-virtual {v1, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n\n    const-string v0, " "\n\n    invoke-virtual {v1, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n\n    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n\n    move-result-object v0\n\n    invoke-virtual {p0, v0}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V\n\n    :cond_f\n    :goto_a\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0010_field__field_public_mAmPmS',
        'type':           'field_add',
        'method':         '.field public mAmPmStyle:I',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field public mAmPmStyle:I',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added field',
    },
    {
        'id':             'p0011_field__field_public_mMiuiS',
        'type':           'field_add',
        'method':         '.field public mMiuiStatusBarClockController:Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field public mMiuiStatusBarClockController:Lcom/android/systemui/statusbar/policy/MiuiStatusBarClockController;',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added field',
    },
    {
        'id':             'p0012_field__field_public_mShowD',
        'type':           'field_add',
        'method':         '.field public mShowDark:Z',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field public mShowDark:Z',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added field',
    },
]
