"""
Legend MiuiSystemUI MTCR patch — modified class.

Target APK   : MiuiSystemUI.apk
Target class : com/android/systemui/statusbar/views/NetworkSpeedView.smali
Patches      : 47
"""
from __future__ import annotations

TARGET_APK           = 'MiuiSystemUI.apk'
TARGET_CLASS         = 'com/android/systemui/statusbar/views/NetworkSpeedView.smali'
CLASS_FALLBACK_NAMES = ['NetworkSpeedView.smali']
CLASS_ANCHORS        = ['invoke-direct {p0, p1}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;)V', 'invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V', 'iput-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;', 'iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z', 'iput v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I']

PATCHES = [
    {
        'id':             'p0000__init_',
        'type':           'method_replace',
        'method':         '.method public constructor <init>(Landroid/content/Context;)V',
        'method_name':    '<init>',
        'method_anchors': ['invoke-direct {p0, p1}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;)V', 'invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V', 'iput-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;'],
        'search':         '.method public constructor <init>(Landroid/content/Context;)V\n    .registers 2\n\n    invoke-direct {p0, p1}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;)V\n\n    const/4 p1, 0x0\n\n    iput-boolean p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    iput p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    new-instance p1, Ljava/util/ArrayList;\n\n    invoke-direct {p1}, Ljava/util/ArrayList;-><init>()V\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;\n\n    const/4 p1, -0x1\n\n    iput p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    new-instance p1, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    invoke-direct {p1, p0}, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;-><init>(Landroid/view/View;)V\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    return-void\n.end method\n',
        'replacement':    '.method public constructor <init>(Landroid/content/Context;)V\n    .registers 4\n\n    invoke-direct {p0, p1}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;)V\n\n    new-instance v0, Ljava/util/ArrayList;\n\n    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V\n\n    iput-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;\n\n    const/4 v0, 0x0\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    const/4 v1, -0x1\n\n    iput v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    new-instance v1, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    invoke-direct {v1, p0}, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;-><init>(Landroid/view/View;)V\n\n    iput-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isStatusBarLocation:Z\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isMove:Z\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0001__init_',
        'type':           'method_replace',
        'method':         '.method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;)V',
        'method_name':    '<init>',
        'method_anchors': ['invoke-direct {p0, p1, p2}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;)V', 'invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V', 'iput-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;'],
        'search':         '.method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;)V\n    .registers 3\n\n    invoke-direct {p0, p1, p2}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;)V\n\n    const/4 p1, 0x0\n\n    iput-boolean p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    iput p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    new-instance p1, Ljava/util/ArrayList;\n\n    invoke-direct {p1}, Ljava/util/ArrayList;-><init>()V\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;\n\n    const/4 p1, -0x1\n\n    iput p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    new-instance p1, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    invoke-direct {p1, p0}, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;-><init>(Landroid/view/View;)V\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    return-void\n.end method\n',
        'replacement':    '.method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;)V\n    .registers 5\n\n    invoke-direct {p0, p1, p2}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;)V\n\n    new-instance v0, Ljava/util/ArrayList;\n\n    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V\n\n    iput-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;\n\n    const/4 v0, 0x0\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    const/4 v1, -0x1\n\n    iput v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    new-instance v1, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    invoke-direct {v1, p0}, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;-><init>(Landroid/view/View;)V\n\n    iput-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isStatusBarLocation:Z\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isMove:Z\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0002__init_',
        'type':           'method_replace',
        'method':         '.method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V',
        'method_name':    '<init>',
        'method_anchors': ['invoke-direct {p0, p1, p2, p3}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V', 'invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V', 'iput-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;'],
        'search':         '.method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V\n    .registers 4\n\n    invoke-direct {p0, p1, p2, p3}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V\n\n    const/4 p1, 0x0\n\n    iput-boolean p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    iput p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    new-instance p1, Ljava/util/ArrayList;\n\n    invoke-direct {p1}, Ljava/util/ArrayList;-><init>()V\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;\n\n    const/4 p1, -0x1\n\n    iput p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    new-instance p1, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    invoke-direct {p1, p0}, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;-><init>(Landroid/view/View;)V\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    return-void\n.end method\n',
        'replacement':    '.method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V\n    .registers 6\n\n    invoke-direct {p0, p1, p2, p3}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V\n\n    new-instance v0, Ljava/util/ArrayList;\n\n    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V\n\n    iput-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;\n\n    const/4 v0, 0x0\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    const/4 v1, -0x1\n\n    iput v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    new-instance v1, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    invoke-direct {v1, p0}, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;-><init>(Landroid/view/View;)V\n\n    iput-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isStatusBarLocation:Z\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isMove:Z\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0003_access_000',
        'type':           'method_add',
        'method':         '.method static synthetic access$000(Lcom/android/systemui/statusbar/views/NetworkSpeedView;)V',
        'method_name':    'access$000',
        'method_anchors': ['invoke-direct {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateDouble()V'],
        'search':         None,
        'replacement':    '.method static synthetic access$000(Lcom/android/systemui/statusbar/views/NetworkSpeedView;)V\n    .registers 1\n\n    invoke-direct {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateDouble()V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0004_access_100',
        'type':           'method_add',
        'method':         '.method static synthetic access$100(Lcom/android/systemui/statusbar/views/NetworkSpeedView;)V',
        'method_name':    'access$100',
        'method_anchors': ['invoke-direct {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateHeight()V'],
        'search':         None,
        'replacement':    '.method static synthetic access$100(Lcom/android/systemui/statusbar/views/NetworkSpeedView;)V\n    .registers 1\n\n    invoke-direct {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateHeight()V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0005_isVisibleInCCAndLC',
        'type':           'method_add',
        'method':         '.method private isVisibleInCCAndLC()Z',
        'method_name':    'isVisibleInCCAndLC',
        'method_anchors': ['invoke-static {v0, v1}, Landroid/preference/SettingsMezoHelper;->getBoolofSettings(Ljava/lang/String;I)Z'],
        'search':         None,
        'replacement':    '.method private isVisibleInCCAndLC()Z\n    .registers 3\n\n    const-string v0, "network_speed_visible_cc_and_lock_screen"\n\n    const/4 v1, 0x1\n\n    invoke-static {v0, v1}, Landroid/preference/SettingsMezoHelper;->getBoolofSettings(Ljava/lang/String;I)Z\n\n    move-result v0\n\n    return v0\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0006_moveNetSpeedGroup',
        'type':           'method_add',
        'method':         '.method private moveNetSpeedGroup()V',
        'method_name':    'moveNetSpeedGroup',
        'method_anchors': ['iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isMove:Z', 'invoke-static {v0}, Lcom/android/systemui/plugins/ControllerStorage;->get(Ljava/lang/Class;)Ljava/lang/Object;', 'iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;'],
        'search':         None,
        'replacement':    '.method private moveNetSpeedGroup()V\n    .registers 8\n\n    const/4 v0, 0x1\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isMove:Z\n\n    const-class v0, Lcom/android/systemui/newstatusbar/controllers/ElementController;\n\n    invoke-static {v0}, Lcom/android/systemui/plugins/ControllerStorage;->get(Ljava/lang/Class;)Ljava/lang/Object;\n\n    move-result-object v0\n\n    check-cast v0, Lcom/android/systemui/newstatusbar/controllers/ElementController;\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;\n\n    invoke-virtual {v0, v1}, Lcom/android/systemui/newstatusbar/controllers/ElementController;->getNetSpeedGroup(Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;)Landroid/view/ViewGroup;\n\n    move-result-object v1\n\n    if-eqz v1, :cond_2\n\n    invoke-virtual {v1}, Landroid/view/ViewGroup;->removeAllViews()V\n\n    iget-object v2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;\n\n    invoke-virtual {v2}, Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;->getLayoutParams()Landroid/view/ViewGroup$LayoutParams;\n\n    move-result-object v2\n\n    iget-object v3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;\n\n    invoke-virtual {p0, v3}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->removeView(Landroid/view/View;)V\n\n    iget-object v3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;\n\n    new-instance v4, Landroid/widget/LinearLayout$LayoutParams;\n\n    const/4 v5, -0x2\n\n    if-eqz v2, :cond_0\n\n    iget v6, v2, Landroid/view/ViewGroup$LayoutParams;->width:I\n\n    goto :goto_0\n\n    :cond_0\n    move v6, v5\n\n    :goto_0\n    if-eqz v2, :cond_1\n\n    iget v5, v2, Landroid/view/ViewGroup$LayoutParams;->height:I\n\n    :cond_1\n    invoke-direct {v4, v6, v5}, Landroid/widget/LinearLayout$LayoutParams;-><init>(II)V\n\n    invoke-virtual {v1, v3, v4}, Landroid/view/ViewGroup;->addView(Landroid/view/View;Landroid/view/ViewGroup$LayoutParams;)V\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getVisibility()I\n\n    move-result v3\n\n    invoke-virtual {p0, v3}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setVisibility(I)V\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->onIconChange()V\n\n    goto :goto_1\n\n    :cond_2\n    const-string v2, "Nastya_super"\n\n    const-string v3, "moveNetSpeedGroup: group = null"\n\n    invoke-static {v2, v3}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I\n\n    :goto_1\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0007_updateDouble',
        'type':           'method_add',
        'method':         '.method private updateDouble()V',
        'method_name':    'updateDouble',
        'method_anchors': ['invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getContext()Landroid/content/Context;', 'invoke-virtual {v0}, Landroid/content/Context;->getContentResolver()Landroid/content/ContentResolver;', 'invoke-static {v0, v1, v2}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I'],
        'search':         None,
        'replacement':    '.method private updateDouble()V\n    .registers 4\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getContext()Landroid/content/Context;\n\n    move-result-object v0\n\n    invoke-virtual {v0}, Landroid/content/Context;->getContentResolver()Landroid/content/ContentResolver;\n\n    move-result-object v0\n\n    const-string v1, "status_bar_show_network_speed"\n\n    const/4 v2, 0x0\n\n    invoke-static {v0, v1, v2}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I\n\n    move-result v0\n\n    const/4 v1, 0x2\n\n    if-lt v0, v1, :cond_0\n\n    const/4 v0, 0x1\n\n    goto :goto_0\n\n    :cond_0\n    move v0, v2\n\n    :goto_0\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isDouble:Z\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    if-eqz v0, :cond_1\n\n    goto :goto_1\n\n    :cond_1\n    const/16 v2, 0x8\n\n    :goto_1\n    invoke-virtual {v1, v2}, Landroid/widget/TextView;->setVisibility(I)V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0008_updateHeight',
        'type':           'method_add',
        'method':         '.method private updateHeight()V',
        'method_name':    'updateHeight',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;', 'invoke-virtual {v0}, Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;->updateHeight()V'],
        'search':         None,
        'replacement':    '.method private updateHeight()V\n    .registers 2\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;\n\n    invoke-virtual {v0}, Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;->updateHeight()V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0009_getBlurRadius',
        'type':           'method_replace',
        'method':         '.method public getBlurRadius()I',
        'method_name':    'getBlurRadius',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;', 'iget v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->blurRadius:I'],
        'search':         '.method public getBlurRadius()I\n    .registers 1\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget p0, p0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->blurRadius:I\n\n    return p0\n.end method\n',
        'replacement':    '.method public getBlurRadius()I\n    .registers 2\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->blurRadius:I\n\n    return v0\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0010_getDeemHide',
        'type':           'method_add',
        'method':         '.method public getDeemHide()Z',
        'method_name':    'getDeemHide',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.method public getDeemHide()Z\n    .registers 2\n\n    const/4 v0, 0x0\n\n    return v0\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0011_getDrawingRect',
        'type':           'method_replace',
        'method':         '.method public final getDrawingRect(Landroid/graphics/Rect;)V',
        'method_name':    'getDrawingRect',
        'method_anchors': ['invoke-super {p0, p1}, Landroid/widget/LinearLayout;->getDrawingRect(Landroid/graphics/Rect;)V', 'invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getTranslationX()F', 'invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getTranslationY()F'],
        'search':         '.method public final getDrawingRect(Landroid/graphics/Rect;)V\n    .registers 4\n\n    invoke-super {p0, p1}, Landroid/widget/LinearLayout;->getDrawingRect(Landroid/graphics/Rect;)V\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getTranslationX()F\n\n    move-result v0\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getTranslationY()F\n\n    move-result p0\n\n    iget v1, p1, Landroid/graphics/Rect;->left:I\n\n    int-to-float v1, v1\n\n    add-float/2addr v1, v0\n\n    float-to-int v1, v1\n\n    iput v1, p1, Landroid/graphics/Rect;->left:I\n\n    iget v1, p1, Landroid/graphics/Rect;->right:I\n\n    int-to-float v1, v1\n\n    add-float/2addr v1, v0\n\n    float-to-int v0, v1\n\n    iput v0, p1, Landroid/graphics/Rect;->right:I\n\n    iget v0, p1, Landroid/graphics/Rect;->top:I\n\n    int-to-float v0, v0\n\n    add-float/2addr v0, p0\n\n    float-to-int v0, v0\n\n    iput v0, p1, Landroid/graphics/Rect;->top:I\n\n    iget v0, p1, Landroid/graphics/Rect;->bottom:I\n\n    int-to-float v0, v0\n\n    add-float/2addr v0, p0\n\n    float-to-int p0, v0\n\n    iput p0, p1, Landroid/graphics/Rect;->bottom:I\n\n    return-void\n.end method\n',
        'replacement':    '.method public final getDrawingRect(Landroid/graphics/Rect;)V\n    .registers 5\n\n    invoke-super {p0, p1}, Landroid/widget/LinearLayout;->getDrawingRect(Landroid/graphics/Rect;)V\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getTranslationX()F\n\n    move-result v0\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getTranslationY()F\n\n    move-result v1\n\n    iget v2, p1, Landroid/graphics/Rect;->left:I\n\n    int-to-float v2, v2\n\n    add-float/2addr v2, v0\n\n    float-to-int v2, v2\n\n    iput v2, p1, Landroid/graphics/Rect;->left:I\n\n    iget v2, p1, Landroid/graphics/Rect;->right:I\n\n    int-to-float v2, v2\n\n    add-float/2addr v2, v0\n\n    float-to-int v2, v2\n\n    iput v2, p1, Landroid/graphics/Rect;->right:I\n\n    iget v2, p1, Landroid/graphics/Rect;->top:I\n\n    int-to-float v2, v2\n\n    add-float/2addr v2, v1\n\n    float-to-int v2, v2\n\n    iput v2, p1, Landroid/graphics/Rect;->top:I\n\n    iget v2, p1, Landroid/graphics/Rect;->bottom:I\n\n    int-to-float v2, v2\n\n    add-float/2addr v2, v1\n\n    float-to-int v2, v2\n\n    iput v2, p1, Landroid/graphics/Rect;->bottom:I\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0012_getNetworkSpeedWidth',
        'type':           'method_replace',
        'method':         '.method public getNetworkSpeedWidth()I',
        'method_name':    'getNetworkSpeedWidth',
        'method_anchors': ['invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getWidth()I', 'invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getPaddingEnd()I', 'invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getPaddingStart()I'],
        'search':         '.method public getNetworkSpeedWidth()I\n    .registers 4\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getWidth()I\n\n    move-result v0\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getPaddingStart()I\n\n    move-result v1\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getPaddingEnd()I\n\n    move-result v2\n\n    add-int/2addr v2, v1\n\n    if-eq v0, v2, :cond_0\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getWidth()I\n\n    move-result p0\n\n    return p0\n\n    :cond_0\n    iget v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    const/4 v1, -0x1\n\n    if-eq v0, v1, :cond_1\n\n    return v0\n\n    :cond_1\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    if-eqz v0, :cond_2\n\n    invoke-virtual {v0}, Landroid/widget/TextView;->getPaint()Landroid/text/TextPaint;\n\n    move-result-object v0\n\n    if-eqz v0, :cond_2\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    invoke-virtual {v0}, Landroid/widget/TextView;->getPaint()Landroid/text/TextPaint;\n\n    move-result-object v0\n\n    const-string v1, "0.00 "\n\n    invoke-virtual {v0, v1}, Landroid/text/TextPaint;->measureText(Ljava/lang/String;)F\n\n    move-result v0\n\n    float-to-int v0, v0\n\n    iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    :cond_2\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    if-eqz v0, :cond_3\n\n    invoke-virtual {v0}, Landroid/widget/TextView;->getPaint()Landroid/text/TextPaint;\n\n    move-result-object v0\n\n    if-eqz v0, :cond_3\n\n    iget v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    int-to-float v0, v0\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    invoke-virtual {v1}, Landroid/widget/TextView;->getPaint()Landroid/text/TextPaint;\n\n    move-result-object v1\n\n    const-string v2, "KB/s "\n\n    invoke-virtual {v1, v2}, Landroid/text/TextPaint;->measureText(Ljava/lang/String;)F\n\n    move-result v1\n\n    invoke-static {v0, v1}, Ljava/lang/Math;->max(FF)F\n\n    move-result v0\n\n    float-to-int v0, v0\n\n    iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    :cond_3\n    iget v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getPaddingStart()I\n\n    move-result v1\n\n    add-int/2addr v1, v0\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getPaddingEnd()I\n\n    move-result v0\n\n    add-int/2addr v0, v1\n\n    iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    return v0\n.end method\n',
        'replacement':    '.method public getNetworkSpeedWidth()I\n    .registers 7\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getWidth()I\n\n    move-result v0\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getPaddingEnd()I\n\n    move-result v1\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getPaddingStart()I\n\n    move-result v2\n\n    add-int/2addr v1, v2\n\n    if-eq v0, v1, :cond_0\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getWidth()I\n\n    move-result v0\n\n    return v0\n\n    :cond_0\n    iget v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    const/4 v1, -0x1\n\n    if-eq v0, v1, :cond_1\n\n    return v0\n\n    :cond_1\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    if-eqz v1, :cond_2\n\n    invoke-virtual {v1}, Landroid/widget/TextView;->getPaint()Landroid/text/TextPaint;\n\n    move-result-object v2\n\n    if-eqz v2, :cond_2\n\n    iget-object v2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    invoke-virtual {v2}, Landroid/widget/TextView;->getPaint()Landroid/text/TextPaint;\n\n    move-result-object v2\n\n    const-string v3, "0.00 "\n\n    invoke-virtual {v2, v3}, Landroid/text/TextPaint;->measureText(Ljava/lang/String;)F\n\n    move-result v2\n\n    float-to-int v2, v2\n\n    iput v2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    :cond_2\n    iget-object v2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    if-eqz v2, :cond_3\n\n    invoke-virtual {v2}, Landroid/widget/TextView;->getPaint()Landroid/text/TextPaint;\n\n    move-result-object v3\n\n    if-eqz v3, :cond_3\n\n    iget v3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    int-to-float v3, v3\n\n    iget-object v4, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    invoke-virtual {v4}, Landroid/widget/TextView;->getPaint()Landroid/text/TextPaint;\n\n    move-result-object v4\n\n    const-string v5, "KB/s "\n\n    invoke-virtual {v4, v5}, Landroid/text/TextPaint;->measureText(Ljava/lang/String;)F\n\n    move-result v4\n\n    invoke-static {v3, v4}, Ljava/lang/Math;->max(FF)F\n\n    move-result v3\n\n    float-to-int v3, v3\n\n    iput v3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    :cond_3\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getPaddingEnd()I\n\n    move-result v3\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getPaddingStart()I\n\n    move-result v4\n\n    add-int/2addr v3, v4\n\n    iget v4, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    add-int/2addr v3, v4\n\n    iput v3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    return v3\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0013_getRemoveFlag',
        'type':           'method_replace',
        'method':         '.method public getRemoveFlag()Z',
        'method_name':    'getRemoveFlag',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;', 'iget-boolean v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z'],
        'search':         '.method public getRemoveFlag()Z\n    .registers 1\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean p0, p0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    return p0\n.end method\n',
        'replacement':    '.method public getRemoveFlag()Z\n    .registers 2\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    return v0\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0014_getSlot',
        'type':           'method_replace',
        'method':         '.method public getSlot()Ljava/lang/String;',
        'method_name':    'getSlot',
        'method_anchors': [],
        'search':         '.method public getSlot()Ljava/lang/String;\n    .registers 1\n\n    const-string p0, "network_speed"\n\n    return-object p0\n.end method\n',
        'replacement':    '.method public getSlot()Ljava/lang/String;\n    .registers 2\n\n    const-string v0, "network_speed"\n\n    return-object v0\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0015_getVisibleState',
        'type':           'method_replace',
        'method':         '.method public getVisibleState()I',
        'method_name':    'getVisibleState',
        'method_anchors': ['iget v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I'],
        'search':         '.method public getVisibleState()I\n    .registers 1\n\n    iget p0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    return p0\n.end method\n',
        'replacement':    '.method public getVisibleState()I\n    .registers 2\n\n    iget v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    return v0\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0016_isIconVisible',
        'type':           'method_replace',
        'method':         '.method public final isIconVisible()Z',
        'method_name':    'isIconVisible',
        'method_anchors': ['iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleByController:Z', 'iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z', 'iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;'],
        'search':         '.method public final isIconVisible()Z\n    .registers 2\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleByController:Z\n\n    if-eqz v0, :cond_0\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    if-eqz v0, :cond_1\n\n    :cond_0\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean p0, p0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    if-eqz p0, :cond_2\n\n    :cond_1\n    const/4 p0, 0x1\n\n    return p0\n\n    :cond_2\n    const/4 p0, 0x0\n\n    return p0\n.end method\n',
        'replacement':    '.method public final isIconVisible()Z\n    .registers 2\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleByController:Z\n\n    if-eqz v0, :cond_0\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    if-eqz v0, :cond_1\n\n    :cond_0\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    if-eqz v0, :cond_2\n\n    :cond_1\n    const/4 v0, 0x1\n\n    goto :goto_0\n\n    :cond_2\n    const/4 v0, 0x0\n\n    :goto_0\n    return v0\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0017_onAttachedToWindow',
        'type':           'method_add',
        'method':         '.method protected onAttachedToWindow()V',
        'method_name':    'onAttachedToWindow',
        'method_anchors': ['invoke-static {v0}, Lcom/android/systemui/plugins/ControllerStorage;->get(Ljava/lang/Class;)Ljava/lang/Object;', 'invoke-virtual {v0, p0}, Lcom/android/systemui/newstatusbar/controllers/NetSpeedColorSizeController;->addCallBack(Lcom/android/systemui/newstatusbar/controllers/IconController$IconCallBack;)V', 'invoke-super {p0}, Landroid/widget/LinearLayout;->onAttachedToWindow()V'],
        'search':         None,
        'replacement':    '.method protected onAttachedToWindow()V\n    .registers 2\n\n    goto :goto_3\n\n    nop\n\n    :goto_0\n    invoke-static {v0}, Lcom/android/systemui/plugins/ControllerStorage;->get(Ljava/lang/Class;)Ljava/lang/Object;\n\n    move-result-object v0\n\n    goto :goto_5\n\n    nop\n\n    :goto_1\n    invoke-virtual {v0, p0}, Lcom/android/systemui/newstatusbar/controllers/NetSpeedColorSizeController;->addCallBack(Lcom/android/systemui/newstatusbar/controllers/IconController$IconCallBack;)V\n\n    goto :goto_2\n\n    nop\n\n    :goto_2\n    return-void\n\n    :goto_3\n    invoke-super {p0}, Landroid/widget/LinearLayout;->onAttachedToWindow()V\n\n    goto :goto_4\n\n    nop\n\n    :goto_4\n    const-class v0, Lcom/android/systemui/newstatusbar/controllers/NetSpeedColorSizeController;\n\n    goto :goto_0\n\n    nop\n\n    :goto_5\n    check-cast v0, Lcom/android/systemui/newstatusbar/controllers/NetSpeedColorSizeController;\n\n    goto :goto_1\n\n    nop\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0018_onDensityOrFontScaleChanged',
        'type':           'method_replace',
        'method':         '.method public final onDensityOrFontScaleChanged()V',
        'method_name':    'onDensityOrFontScaleChanged',
        'method_anchors': ['invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateResources$4()V'],
        'search':         '.method public final onDensityOrFontScaleChanged()V\n    .registers 1\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateResources$4()V\n\n    return-void\n.end method\n',
        'replacement':    '.method public final onDensityOrFontScaleChanged()V\n    .registers 1\n    .annotation system Ldalvik/annotation/Throws;\n        value = {\n            Landroid/content/res/Resources$NotFoundException;\n        }\n    .end annotation\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateResources$4()V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0019_onDetachedFromWindow',
        'type':           'method_add',
        'method':         '.method protected onDetachedFromWindow()V',
        'method_name':    'onDetachedFromWindow',
        'method_anchors': ['invoke-static {v0}, Lcom/android/systemui/plugins/ControllerStorage;->get(Ljava/lang/Class;)Ljava/lang/Object;', 'invoke-virtual {v0}, Landroid/view/ViewGroup;->removeAllViews()V', 'iput-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;'],
        'search':         None,
        'replacement':    '.method protected onDetachedFromWindow()V\n    .registers 3\n\n    goto :goto_d\n\n    nop\n\n    :goto_0\n    invoke-static {v0}, Lcom/android/systemui/plugins/ControllerStorage;->get(Ljava/lang/Class;)Ljava/lang/Object;\n\n    move-result-object v0\n\n    goto :goto_b\n\n    nop\n\n    :goto_1\n    invoke-virtual {v0}, Landroid/view/ViewGroup;->removeAllViews()V\n\n    :goto_2\n    goto :goto_12\n\n    nop\n\n    :goto_3\n    iput-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;\n\n    goto :goto_10\n\n    nop\n\n    :goto_4\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;\n\n    goto :goto_c\n\n    nop\n\n    :goto_5\n    invoke-virtual {v0, p0}, Lcom/android/systemui/newstatusbar/controllers/NetSpeedColorSizeController;->removeCallBack(Lcom/android/systemui/newstatusbar/controllers/IconController$IconCallBack;)V\n\n    goto :goto_14\n\n    nop\n\n    :goto_6\n    invoke-static {v0}, Lcom/android/systemui/plugins/ControllerStorage;->get(Ljava/lang/Class;)Ljava/lang/Object;\n\n    move-result-object v0\n\n    goto :goto_15\n\n    nop\n\n    :goto_7\n    const-class v0, Lcom/android/systemui/newstatusbar/controllers/ElementController;\n\n    goto :goto_6\n\n    nop\n\n    :goto_8\n    const-class v0, Lcom/android/systemui/newstatusbar/controllers/NetSpeedColorSizeController;\n\n    goto :goto_0\n\n    nop\n\n    :goto_9\n    return-void\n\n    :goto_a\n    if-nez v0, :cond_0\n\n    goto :goto_17\n\n    :cond_0\n    goto :goto_4\n\n    nop\n\n    :goto_b\n    check-cast v0, Lcom/android/systemui/newstatusbar/controllers/NetSpeedColorSizeController;\n\n    goto :goto_5\n\n    nop\n\n    :goto_c\n    if-nez v0, :cond_1\n\n    goto :goto_17\n\n    :cond_1\n    goto :goto_7\n\n    nop\n\n    :goto_d\n    invoke-super {p0}, Landroid/widget/LinearLayout;->onDetachedFromWindow()V\n\n    goto :goto_8\n\n    nop\n\n    :goto_e\n    iput-boolean v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isMove:Z\n\n    goto :goto_16\n\n    nop\n\n    :goto_f\n    if-nez v0, :cond_2\n\n    goto :goto_2\n\n    :cond_2\n    goto :goto_1\n\n    nop\n\n    :goto_10\n    const/4 v1, 0x0\n\n    goto :goto_e\n\n    nop\n\n    :goto_11\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;\n\n    goto :goto_13\n\n    nop\n\n    :goto_12\n    const/4 v1, 0x0\n\n    goto :goto_3\n\n    nop\n\n    :goto_13\n    invoke-virtual {v0, v1}, Lcom/android/systemui/newstatusbar/controllers/ElementController;->getNetSpeedGroup(Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;)Landroid/view/ViewGroup;\n\n    move-result-object v0\n\n    goto :goto_f\n\n    nop\n\n    :goto_14\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isMove:Z\n\n    goto :goto_a\n\n    nop\n\n    :goto_15\n    check-cast v0, Lcom/android/systemui/newstatusbar/controllers/ElementController;\n\n    goto :goto_11\n\n    nop\n\n    :goto_16\n    iput-boolean v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isStatusBarLocation:Z\n\n    :goto_17\n    goto :goto_9\n\n    nop\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0020_onFinishInflate',
        'type':           'method_replace',
        'method':         '.method public final onFinishInflate()V',
        'method_name':    'onFinishInflate',
        'method_anchors': ['invoke-super {p0}, Landroid/widget/LinearLayout;->onFinishInflate()V', 'invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getContext()Landroid/content/Context;', 'invoke-static {v0, v1}, Landroid/Utils/Utils;->IDtoID(Landroid/content/Context;Ljava/lang/String;)I'],
        'search':         '.method public final onFinishInflate()V\n    .registers 2\n\n    invoke-super {p0}, Landroid/widget/LinearLayout;->onFinishInflate()V\n\n    const v0, 0x7f0b0852\n\n    invoke-virtual {p0, v0}, Landroid/widget/LinearLayout;->findViewById(I)Landroid/view/View;\n\n    move-result-object v0\n\n    check-cast v0, Landroid/widget/TextView;\n\n    iput-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    const v0, 0x7f0b0853\n\n    invoke-virtual {p0, v0}, Landroid/widget/LinearLayout;->findViewById(I)Landroid/view/View;\n\n    move-result-object v0\n\n    check-cast v0, Landroid/widget/TextView;\n\n    iput-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    const v0, 0x7f0b0851\n\n    invoke-virtual {p0, v0}, Landroid/widget/LinearLayout;->findViewById(I)Landroid/view/View;\n\n    move-result-object v0\n\n    iput-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Landroid/view/View;\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateResources$4()V\n\n    return-void\n.end method\n',
        'replacement':    '.method public final onFinishInflate()V\n    .registers 3\n    .annotation system Ldalvik/annotation/Throws;\n        value = {\n            Landroid/content/res/Resources$NotFoundException;\n        }\n    .end annotation\n\n    invoke-super {p0}, Landroid/widget/LinearLayout;->onFinishInflate()V\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getContext()Landroid/content/Context;\n\n    move-result-object v0\n\n    const-string v1, "network_speed_number"\n\n    invoke-static {v0, v1}, Landroid/Utils/Utils;->IDtoID(Landroid/content/Context;Ljava/lang/String;)I\n\n    move-result v1\n\n    invoke-virtual {p0, v1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->findViewById(I)Landroid/view/View;\n\n    move-result-object v1\n\n    check-cast v1, Landroid/widget/TextView;\n\n    iput-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    const-string v1, "network_speed_unit"\n\n    invoke-static {v0, v1}, Landroid/Utils/Utils;->IDtoID(Landroid/content/Context;Ljava/lang/String;)I\n\n    move-result v1\n\n    invoke-virtual {p0, v1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->findViewById(I)Landroid/view/View;\n\n    move-result-object v1\n\n    check-cast v1, Landroid/widget/TextView;\n\n    iput-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    const-string v1, "network_speed_container"\n\n    invoke-static {v0, v1}, Landroid/Utils/Utils;->IDtoID(Landroid/content/Context;Ljava/lang/String;)I\n\n    move-result v1\n\n    invoke-virtual {p0, v1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->findViewById(I)Landroid/view/View;\n\n    move-result-object v1\n\n    check-cast v1, Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;\n\n    iput-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateResources$4()V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0021_onIconChange',
        'type':           'method_add',
        'method':         '.method public onIconChange()V',
        'method_name':    'onIconChange',
        'method_anchors': ['invoke-direct {v0, p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView$1;-><init>(Lcom/android/systemui/statusbar/views/NetworkSpeedView;)V', 'invoke-virtual {p0, v0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->post(Ljava/lang/Runnable;)Z'],
        'search':         None,
        'replacement':    '.method public onIconChange()V\n    .registers 2\n\n    new-instance v0, Lcom/android/systemui/statusbar/views/NetworkSpeedView$1;\n\n    invoke-direct {v0, p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView$1;-><init>(Lcom/android/systemui/statusbar/views/NetworkSpeedView;)V\n\n    invoke-virtual {p0, v0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->post(Ljava/lang/Runnable;)Z\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0022_onMiuiThemeChanged_1',
        'type':           'method_replace',
        'method':         '.method public final onMiuiThemeChanged$1(Z)V',
        'method_name':    'onMiuiThemeChanged$1',
        'method_anchors': ['invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateResources$4()V'],
        'search':         '.method public final onMiuiThemeChanged$1(Z)V\n    .registers 2\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateResources$4()V\n\n    return-void\n.end method\n',
        'replacement':    '.method public final onMiuiThemeChanged$1(Z)V\n    .registers 2\n    .annotation system Ldalvik/annotation/Throws;\n        value = {\n            Landroid/content/res/Resources$NotFoundException;\n        }\n    .end annotation\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateResources$4()V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0023_onVisibilityAggregated',
        'type':           'method_add',
        'method':         '.method public final onVisibilityAggregated(Z)V',
        'method_name':    'onVisibilityAggregated',
        'method_anchors': ['invoke-super {p0, p1}, Landroid/widget/LinearLayout;->onVisibilityAggregated(Z)V', 'iput-boolean p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mShown:Z', 'invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateNetworkSpeed()V'],
        'search':         None,
        'replacement':    '.method public final onVisibilityAggregated(Z)V\n    .registers 2\n\n    invoke-super {p0, p1}, Landroid/widget/LinearLayout;->onVisibilityAggregated(Z)V\n\n    iput-boolean p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mShown:Z\n\n    if-eqz p1, :cond_0\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateNetworkSpeed()V\n\n    :cond_0\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0024_performRemove',
        'type':           'method_replace',
        'method':         '.method public final performRemove()V',
        'method_name':    'performRemove',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;', 'iget-boolean v1, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z', 'iput-boolean v1, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z'],
        'search':         '.method public final performRemove()V\n    .registers 2\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    if-nez v0, :cond_0\n\n    return-void\n\n    :cond_0\n    const/4 v0, 0x0\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->view:Landroid/view/View;\n\n    const/16 v0, 0x8\n\n    invoke-virtual {p0, v0}, Landroid/view/View;->setVisibility(I)V\n\n    return-void\n.end method\n',
        'replacement':    '.method public final performRemove()V\n    .registers 4\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean v1, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    if-eqz v1, :cond_0\n\n    const/4 v1, 0x0\n\n    iput-boolean v1, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    iget-object v1, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->view:Landroid/view/View;\n\n    const/16 v2, 0x8\n\n    invoke-virtual {v1, v2}, Landroid/view/View;->setVisibility(I)V\n\n    :cond_0\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0025_setAnimationEnable',
        'type':           'method_replace',
        'method':         '.method public setAnimationEnable(Z)V',
        'method_name':    'setAnimationEnable',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;', 'iput-boolean p1, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->animateEnable:Z'],
        'search':         '.method public setAnimationEnable(Z)V\n    .registers 2\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iput-boolean p1, p0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->animateEnable:Z\n\n    return-void\n.end method\n',
        'replacement':    '.method public setAnimationEnable(Z)V\n    .registers 3\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iput-boolean p1, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->animateEnable:Z\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0026_setBlurRadius',
        'type':           'method_replace',
        'method':         '.method public setBlurRadius(I)V',
        'method_name':    'setBlurRadius',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;', 'invoke-virtual {v0, p1}, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->setBlurRadius(I)V'],
        'search':         '.method public setBlurRadius(I)V\n    .registers 2\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    invoke-virtual {p0, p1}, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->setBlurRadius(I)V\n\n    return-void\n.end method\n',
        'replacement':    '.method public setBlurRadius(I)V\n    .registers 3\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    invoke-virtual {v0, p1}, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->setBlurRadius(I)V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0027_setDeemHide',
        'type':           'method_add',
        'method':         '.method public setDeemHide(Z)V',
        'method_name':    'setDeemHide',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.method public setDeemHide(Z)V\n    .registers 2\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0028_setDripEnd',
        'type':           'method_add',
        'method':         '.method public setDripEnd(Z)V',
        'method_name':    'setDripEnd',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.method public setDripEnd(Z)V\n    .registers 2\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0029_setNetworkSpeed',
        'type':           'method_replace',
        'method':         '.method public setNetworkSpeed(Ljava/lang/String;Ljava/lang/String;)V',
        'method_name':    'setNetworkSpeed',
        'method_anchors': ['iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumber:Ljava/lang/CharSequence;', 'iput-object p2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnit:Ljava/lang/CharSequence;', 'iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleByController:Z'],
        'search':         '.method public setNetworkSpeed(Ljava/lang/String;Ljava/lang/String;)V\n    .registers 3\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumber:Ljava/lang/CharSequence;\n\n    iput-object p2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnit:Ljava/lang/CharSequence;\n\n    iget-boolean p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleByController:Z\n\n    if-eqz p1, :cond_0\n\n    iget-boolean p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    if-nez p1, :cond_0\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateNetworkSpeed()V\n\n    :cond_0\n    return-void\n.end method\n',
        'replacement':    '.method public setNetworkSpeed(Ljava/lang/String;Ljava/lang/String;)V\n    .registers 4\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumber:Ljava/lang/CharSequence;\n\n    iput-object p2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnit:Ljava/lang/CharSequence;\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleByController:Z\n\n    if-eqz v0, :cond_1\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    if-nez v0, :cond_1\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mShown:Z\n\n    if-nez v0, :cond_0\n\n    goto :goto_0\n\n    :cond_0\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateNetworkSpeed()V\n\n    return-void\n\n    :cond_1\n    :goto_0\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0030_setRemove',
        'type':           'method_replace',
        'method':         '.method public setRemove(Z)V',
        'method_name':    'setRemove',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;', 'iput-boolean p1, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z'],
        'search':         '.method public setRemove(Z)V\n    .registers 2\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iput-boolean p1, p0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    return-void\n.end method\n',
        'replacement':    '.method public setRemove(Z)V\n    .registers 3\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iput-boolean p1, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0031_setSlot',
        'type':           'method_add',
        'method':         '.method public setSlot(Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;)V',
        'method_name':    'setSlot',
        'method_anchors': ['iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isStatusBarLocation:Z', 'iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;', 'invoke-direct {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->moveNetSpeedGroup()V'],
        'search':         None,
        'replacement':    '.method public setSlot(Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;)V\n    .registers 3\n\n    const/4 v0, 0x1\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isStatusBarLocation:Z\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;\n\n    invoke-direct {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->moveNetSpeedGroup()V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0032_setStaticDrawableColor',
        'type':           'method_replace',
        'method':         '.method public setStaticDrawableColor(II)V',
        'method_name':    'setStaticDrawableColor',
        'method_anchors': ['invoke-virtual {p0, p1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setStaticDrawableColor(I)V'],
        'search':         '.method public setStaticDrawableColor(II)V\n    .registers 3\n\n    invoke-interface {p0, p1}, Lcom/android/systemui/statusbar/StatusIconDisplayable;->setStaticDrawableColor(I)V\n\n    return-void\n.end method\n',
        'replacement':    '.method public setStaticDrawableColor(II)V\n    .registers 3\n\n    invoke-virtual {p0, p1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setStaticDrawableColor(I)V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0033_setVisibility',
        'type':           'method_add',
        'method':         '.method public setVisibility(I)V',
        'method_name':    'setVisibility',
        'method_anchors': ['invoke-super {p0, p1}, Landroid/widget/LinearLayout;->setVisibility(I)V', 'iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;', 'invoke-virtual {v0, p1}, Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;->setVisibility(I)V'],
        'search':         None,
        'replacement':    '.method public setVisibility(I)V\n    .registers 3\n\n    invoke-super {p0, p1}, Landroid/widget/LinearLayout;->setVisibility(I)V\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;\n\n    if-eqz v0, :cond_0\n\n    invoke-virtual {v0, p1}, Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;->setVisibility(I)V\n\n    :cond_0\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added method',
    },
    {
        'id':             'p0034_setVisibleState',
        'type':           'method_replace',
        'method':         '.method public setVisibleState(I)V',
        'method_name':    'setVisibleState',
        'method_anchors': ['invoke-virtual {p0, p1, v0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setVisibleState(IZ)V'],
        'search':         '.method public setVisibleState(I)V\n    .registers 3\n\n    const/4 v0, 0x0\n\n    invoke-interface {p0, p1, v0}, Lcom/android/systemui/statusbar/StatusIconDisplayable;->setVisibleState(IZ)V\n\n    return-void\n.end method\n',
        'replacement':    '.method public setVisibleState(I)V\n    .registers 3\n\n    const/4 v0, 0x0\n\n    invoke-virtual {p0, p1, v0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setVisibleState(IZ)V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0035_setVisibleState',
        'type':           'method_replace',
        'method':         '.method public setVisibleState(IZ)V',
        'method_name':    'setVisibleState',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;', 'iget-boolean v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z', 'iget v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I'],
        'search':         '.method public setVisibleState(IZ)V\n    .registers 3\n\n    iget-object p2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean p2, p2, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    if-eqz p2, :cond_0\n\n    goto :goto_1\n\n    :cond_0\n    iget p2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    if-eq p2, p1, :cond_2\n\n    iput p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Landroid/view/View;\n\n    const/4 p2, 0x2\n\n    if-eq p1, p2, :cond_1\n\n    const/4 p1, 0x0\n\n    goto :goto_0\n\n    :cond_1\n    const/4 p1, 0x4\n\n    :goto_0\n    invoke-virtual {p0, p1}, Landroid/view/View;->setVisibility(I)V\n\n    :cond_2\n    :goto_1\n    return-void\n.end method\n',
        'replacement':    '.method public setVisibleState(IZ)V\n    .registers 5\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    if-nez v0, :cond_3\n\n    iget v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    if-ne v0, p1, :cond_0\n\n    goto :goto_1\n\n    :cond_0\n    iput p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;\n\n    if-eqz v0, :cond_2\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isStatusBarLocation:Z\n\n    if-nez v0, :cond_2\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;\n\n    const/4 v1, 0x2\n\n    if-eq p1, v1, :cond_1\n\n    const/4 v1, 0x0\n\n    goto :goto_0\n\n    :cond_1\n    const/4 v1, 0x4\n\n    :goto_0\n    invoke-virtual {v0, v1}, Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;->setVisibility(I)V\n\n    :cond_2\n    return-void\n\n    :cond_3\n    :goto_1\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0036_toString',
        'type':           'method_replace',
        'method':         '.method public final toString()Ljava/lang/String;',
        'method_name':    'toString',
        'method_anchors': ['invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getContext()Landroid/content/Context;', 'invoke-static {v0, v1}, Landroid/Utils/Utils;->IDtoID(Landroid/content/Context;Ljava/lang/String;)I', 'invoke-virtual {p0, v0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getTag(I)Ljava/lang/Object;'],
        'search':         '.method public final toString()Ljava/lang/String;\n    .registers 3\n\n    const v0, 0x7f0b0b75\n\n    invoke-virtual {p0, v0}, Landroid/widget/LinearLayout;->getTag(I)Ljava/lang/Object;\n\n    move-result-object v0\n\n    instance-of v1, v0, Lcom/android/systemui/statusbar/views/NewStatusIconState;\n\n    if-eqz v1, :cond_0\n\n    check-cast v0, Lcom/android/systemui/statusbar/views/NewStatusIconState;\n\n    iget-boolean v0, v0, Lcom/android/systemui/statusbar/views/NewStatusIconState;->hiddenBySpace:Z\n\n    goto :goto_0\n\n    :cond_0\n    const/4 v0, 0x0\n\n    :goto_0\n    new-instance v1, Ljava/lang/StringBuilder;\n\n    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V\n\n    invoke-super {p0}, Landroid/widget/LinearLayout;->toString()Ljava/lang/String;\n\n    move-result-object p0\n\n    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n\n    const-string p0, " hideBySpace =  "\n\n    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n\n    invoke-virtual {v1, v0}, Ljava/lang/StringBuilder;->append(Z)Ljava/lang/StringBuilder;\n\n    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n\n    move-result-object p0\n\n    return-object p0\n.end method\n',
        'replacement':    '.method public final toString()Ljava/lang/String;\n    .registers 4\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getContext()Landroid/content/Context;\n\n    move-result-object v0\n\n    const-string v1, "status_bar_view_state_tag"\n\n    invoke-static {v0, v1}, Landroid/Utils/Utils;->IDtoID(Landroid/content/Context;Ljava/lang/String;)I\n\n    move-result v0\n\n    invoke-virtual {p0, v0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getTag(I)Ljava/lang/Object;\n\n    move-result-object v0\n\n    new-instance v1, Ljava/lang/StringBuilder;\n\n    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V\n\n    invoke-super {p0}, Landroid/widget/LinearLayout;->toString()Ljava/lang/String;\n\n    move-result-object v2\n\n    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n\n    move-result-object v1\n\n    const-string v2, " hideBySpace =  "\n\n    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n\n    move-result-object v1\n\n    instance-of v2, v0, Lcom/android/systemui/statusbar/views/NewStatusIconState;\n\n    if-eqz v2, :cond_0\n\n    move-object v2, v0\n\n    check-cast v2, Lcom/android/systemui/statusbar/views/NewStatusIconState;\n\n    iget-boolean v2, v2, Lcom/android/systemui/statusbar/views/NewStatusIconState;->hiddenBySpace:Z\n\n    if-eqz v2, :cond_0\n\n    const/4 v2, 0x1\n\n    goto :goto_0\n\n    :cond_0\n    const/4 v2, 0x0\n\n    :goto_0\n    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Z)Ljava/lang/StringBuilder;\n\n    move-result-object v1\n\n    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n\n    move-result-object v1\n\n    return-object v1\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0037_updateLightDarkTint_1',
        'type':           'method_replace',
        'method':         '.method public final updateLightDarkTint$1(Ljava/util/ArrayList;FIIIZ)V',
        'method_name':    'updateLightDarkTint$1',
        'method_anchors': ['iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;', 'iput p2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mDarkIntensity:F', 'iput p3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mTint:I'],
        'search':         '.method public final updateLightDarkTint$1(Ljava/util/ArrayList;FIIIZ)V\n    .registers 8\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;\n\n    iput p2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mDarkIntensity:F\n\n    iput p3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mTint:I\n\n    if-eqz p6, :cond_0\n\n    iget-object p2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    invoke-static {p1, p0, p3}, Lcom/android/systemui/statusbar/DarkIconDispatcherExt;->getTint(Ljava/util/Collection;Landroid/view/View;I)I\n\n    move-result p4\n\n    invoke-virtual {p2, p4}, Landroid/widget/TextView;->setTextColor(I)V\n\n    iget-object p2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    invoke-static {p1, p0, p3}, Lcom/android/systemui/statusbar/DarkIconDispatcherExt;->getTint(Ljava/util/Collection;Landroid/view/View;I)I\n\n    move-result p0\n\n    invoke-virtual {p2, p0}, Landroid/widget/TextView;->setTextColor(I)V\n\n    return-void\n\n    :cond_0\n    iget-object p3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    invoke-static {p1, p0, p2}, Lcom/android/systemui/statusbar/DarkIconDispatcherExt;->getDarkIntensity(Ljava/util/ArrayList;Landroid/view/View;F)F\n\n    move-result p6\n\n    const/4 v0, 0x0\n\n    cmpl-float p6, p6, v0\n\n    if-lez p6, :cond_1\n\n    move p6, p5\n\n    goto :goto_0\n\n    :cond_1\n    move p6, p4\n\n    :goto_0\n    invoke-virtual {p3, p6}, Landroid/widget/TextView;->setTextColor(I)V\n\n    iget-object p3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    invoke-static {p1, p0, p2}, Lcom/android/systemui/statusbar/DarkIconDispatcherExt;->getDarkIntensity(Ljava/util/ArrayList;Landroid/view/View;F)F\n\n    move-result p0\n\n    cmpl-float p0, p0, v0\n\n    if-lez p0, :cond_2\n\n    move p4, p5\n\n    :cond_2\n    invoke-virtual {p3, p4}, Landroid/widget/TextView;->setTextColor(I)V\n\n    return-void\n.end method\n',
        'replacement':    '.method public final updateLightDarkTint$1(Ljava/util/ArrayList;FIIIZ)V\n    .registers 10\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;\n\n    iput p2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mDarkIntensity:F\n\n    iput p3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mTint:I\n\n    if-eqz p6, :cond_0\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    invoke-static {p1, p0, p3}, Lcom/android/systemui/statusbar/DarkIconDispatcherExt;->getTint(Ljava/util/Collection;Landroid/view/View;I)I\n\n    move-result v1\n\n    invoke-virtual {v0, v1}, Landroid/widget/TextView;->setTextColor(I)V\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    invoke-static {p1, p0, p3}, Lcom/android/systemui/statusbar/DarkIconDispatcherExt;->getTint(Ljava/util/Collection;Landroid/view/View;I)I\n\n    move-result v1\n\n    invoke-virtual {v0, v1}, Landroid/widget/TextView;->setTextColor(I)V\n\n    return-void\n\n    :cond_0\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    invoke-static {p1, p0, p2}, Lcom/android/systemui/statusbar/DarkIconDispatcherExt;->getDarkIntensity(Ljava/util/ArrayList;Landroid/view/View;F)F\n\n    move-result v1\n\n    const/4 v2, 0x0\n\n    cmpl-float v1, v1, v2\n\n    if-lez v1, :cond_1\n\n    move v1, p5\n\n    goto :goto_0\n\n    :cond_1\n    move v1, p4\n\n    :goto_0\n    invoke-virtual {v0, v1}, Landroid/widget/TextView;->setTextColor(I)V\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    invoke-static {p1, p0, p2}, Lcom/android/systemui/statusbar/DarkIconDispatcherExt;->getDarkIntensity(Ljava/util/ArrayList;Landroid/view/View;F)F\n\n    move-result v1\n\n    cmpl-float v1, v1, v2\n\n    if-lez v1, :cond_2\n\n    move p4, p5\n\n    :cond_2\n    invoke-virtual {v0, p4}, Landroid/widget/TextView;->setTextColor(I)V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0038_updateNetworkSpeed',
        'type':           'method_replace',
        'method':         '.method public final updateNetworkSpeed()V',
        'method_name':    'updateNetworkSpeed',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumber:Ljava/lang/CharSequence;', 'iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;', 'invoke-virtual {v1}, Landroid/widget/TextView;->getText()Ljava/lang/CharSequence;'],
        'search':         '.method public final updateNetworkSpeed()V\n    .registers 4\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumber:Ljava/lang/CharSequence;\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    invoke-virtual {v1}, Landroid/widget/TextView;->getText()Ljava/lang/CharSequence;\n\n    move-result-object v1\n\n    invoke-static {v0, v1}, Landroid/text/TextUtils;->equals(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Z\n\n    move-result v0\n\n    const-string v1, " "\n\n    if-nez v0, :cond_0\n\n    new-instance v0, Ljava/lang/StringBuilder;\n\n    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n\n    iget-object v2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumber:Ljava/lang/CharSequence;\n\n    invoke-virtual {v0, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;\n\n    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n\n    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n\n    move-result-object v0\n\n    iget-object v2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    invoke-virtual {v2, v0}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V\n\n    :cond_0\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnit:Ljava/lang/CharSequence;\n\n    iget-object v2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    invoke-virtual {v2}, Landroid/widget/TextView;->getText()Ljava/lang/CharSequence;\n\n    move-result-object v2\n\n    invoke-static {v0, v2}, Landroid/text/TextUtils;->equals(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Z\n\n    move-result v0\n\n    if-nez v0, :cond_1\n\n    new-instance v0, Ljava/lang/StringBuilder;\n\n    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n\n    iget-object v2, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnit:Ljava/lang/CharSequence;\n\n    invoke-virtual {v0, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;\n\n    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n\n    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n\n    move-result-object v0\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    invoke-virtual {v1, v0}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V\n\n    :cond_1\n    new-instance v0, Ljava/lang/StringBuilder;\n\n    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumber:Ljava/lang/CharSequence;\n\n    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;\n\n    const-string v1, ""\n\n    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnit:Ljava/lang/CharSequence;\n\n    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;\n\n    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n\n    move-result-object v0\n\n    invoke-virtual {p0, v0}, Landroid/widget/LinearLayout;->setContentDescription(Ljava/lang/CharSequence;)V\n\n    return-void\n.end method\n',
        'replacement':    '.method public final updateNetworkSpeed()V\n    .registers 3\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumber:Ljava/lang/CharSequence;\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    invoke-virtual {v1}, Landroid/widget/TextView;->getText()Ljava/lang/CharSequence;\n\n    move-result-object v1\n\n    invoke-static {v0, v1}, Landroid/text/TextUtils;->equals(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Z\n\n    move-result v0\n\n    if-nez v0, :cond_0\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumber:Ljava/lang/CharSequence;\n\n    invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V\n\n    :cond_0\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnit:Ljava/lang/CharSequence;\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    invoke-virtual {v1}, Landroid/widget/TextView;->getText()Ljava/lang/CharSequence;\n\n    move-result-object v1\n\n    invoke-static {v0, v1}, Landroid/text/TextUtils;->equals(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Z\n\n    move-result v0\n\n    if-nez v0, :cond_1\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnit:Ljava/lang/CharSequence;\n\n    invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V\n\n    :cond_1\n    new-instance v0, Ljava/lang/StringBuilder;\n\n    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumber:Ljava/lang/CharSequence;\n\n    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;\n\n    move-result-object v0\n\n    const-string v1, ""\n\n    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n\n    move-result-object v0\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnit:Ljava/lang/CharSequence;\n\n    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;\n\n    move-result-object v0\n\n    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n\n    move-result-object v0\n\n    invoke-virtual {p0, v0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setContentDescription(Ljava/lang/CharSequence;)V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0039_updateResources_4',
        'type':           'method_replace',
        'method':         '.method public final updateResources$4()V',
        'method_name':    'updateResources$4',
        'method_anchors': ['iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I', 'iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;', 'invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getContext()Landroid/content/Context;'],
        'search':         '.method public final updateResources$4()V\n    .registers 10\n\n    const/4 v0, -0x1\n\n    iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    const v1, 0x7f150632\n\n    invoke-virtual {v0, v1}, Landroid/widget/TextView;->setTextAppearance(I)V\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    const v1, 0x7f150633\n\n    invoke-virtual {v0, v1}, Landroid/widget/TextView;->setTextAppearance(I)V\n\n    iget-object v3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;\n\n    iget v4, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mDarkIntensity:F\n\n    iget v5, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mTint:I\n\n    iget v6, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mLightColor:I\n\n    iget v7, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mDarkColor:I\n\n    iget-boolean v8, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mUseTint:Z\n\n    move-object v2, p0\n\n    invoke-virtual/range {v2 .. v8}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateLightDarkTint$1(Ljava/util/ArrayList;FIIIZ)V\n\n    invoke-virtual {v2}, Landroid/widget/LinearLayout;->getResources()Landroid/content/res/Resources;\n\n    move-result-object p0\n\n    const v0, 0x7f0718a9\n\n    invoke-virtual {p0, v0}, Landroid/content/res/Resources;->getDimensionPixelSize(I)I\n\n    move-result p0\n\n    invoke-virtual {v2}, Landroid/widget/LinearLayout;->getResources()Landroid/content/res/Resources;\n\n    move-result-object v0\n\n    const v1, 0x7f0718ad\n\n    invoke-virtual {v0, v1}, Landroid/content/res/Resources;->getDimensionPixelSize(I)I\n\n    move-result v0\n\n    iget-object v1, v2, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    neg-int p0, p0\n\n    int-to-float p0, p0\n\n    invoke-virtual {v1, p0}, Landroid/widget/TextView;->setTranslationY(F)V\n\n    iget-object p0, v2, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    int-to-float v0, v0\n\n    invoke-virtual {p0, v0}, Landroid/widget/TextView;->setTranslationY(F)V\n\n    return-void\n.end method\n',
        'replacement':    '.method public final updateResources$4()V\n    .registers 10\n    .annotation system Ldalvik/annotation/Throws;\n        value = {\n            Landroid/content/res/Resources$NotFoundException;\n        }\n    .end annotation\n\n    const/4 v0, -0x1\n\n    iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mEmptyWidth:I\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedNumberText:Landroid/widget/TextView;\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getContext()Landroid/content/Context;\n\n    move-result-object v1\n\n    const-string v2, "TextAppearance.StatusBar.NetWorkSpeedNumber"\n\n    invoke-static {v1, v2}, Landroid/Utils/Utils;->StyleToID(Landroid/content/Context;Ljava/lang/String;)I\n\n    move-result v1\n\n    invoke-virtual {v0, v1}, Landroid/widget/TextView;->setTextAppearance(I)V\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mNetworkSpeedUnitText:Landroid/widget/TextView;\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getContext()Landroid/content/Context;\n\n    move-result-object v1\n\n    const-string v2, "TextAppearance.StatusBar.NetWorkSpeedUnit"\n\n    invoke-static {v1, v2}, Landroid/Utils/Utils;->StyleToID(Landroid/content/Context;Ljava/lang/String;)I\n\n    move-result v1\n\n    invoke-virtual {v0, v1}, Landroid/widget/TextView;->setTextAppearance(I)V\n\n    iget-object v3, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mAreas:Ljava/util/ArrayList;\n\n    iget v4, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mDarkIntensity:F\n\n    iget v5, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mTint:I\n\n    iget v6, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mLightColor:I\n\n    iget v7, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mDarkColor:I\n\n    iget-boolean v8, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mUseTint:Z\n\n    move-object v2, p0\n\n    invoke-virtual/range {v2 .. v8}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateLightDarkTint$1(Ljava/util/ArrayList;FIIIZ)V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0040_updateVisibility',
        'type':           'method_replace',
        'method':         '.method public final updateVisibility()V',
        'method_name':    'updateVisibility',
        'method_anchors': ['iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleByController:Z', 'iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z', 'iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isStatusBarLocation:Z'],
        'search':         '.method public final updateVisibility()V\n    .registers 4\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleByController:Z\n\n    const/4 v1, 0x0\n\n    if-eqz v0, :cond_1\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    if-nez v0, :cond_1\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    if-eqz v0, :cond_0\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getVisibility()I\n\n    move-result v0\n\n    if-nez v0, :cond_0\n\n    const/4 v0, 0x2\n\n    iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateNetworkSpeed()V\n\n    invoke-virtual {p0, v1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setRemove(Z)V\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->requestLayout()V\n\n    return-void\n\n    :cond_0\n    invoke-virtual {p0, v1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setRemove(Z)V\n\n    invoke-virtual {p0, v1}, Landroid/widget/LinearLayout;->setVisibility(I)V\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateNetworkSpeed()V\n\n    return-void\n\n    :cond_1\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getVisibility()I\n\n    move-result v0\n\n    const/16 v2, 0x8\n\n    if-eq v0, v2, :cond_3\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->animateEnable:Z\n\n    if-nez v0, :cond_2\n\n    goto :goto_0\n\n    :cond_2\n    const/4 v0, 0x1\n\n    invoke-virtual {p0, v0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setRemove(Z)V\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->requestLayout()V\n\n    return-void\n\n    :cond_3\n    :goto_0\n    invoke-virtual {p0, v1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setRemove(Z)V\n\n    invoke-virtual {p0, v2}, Landroid/widget/LinearLayout;->setVisibility(I)V\n\n    return-void\n.end method\n',
        'replacement':    '.method public final updateVisibility()V\n    .registers 4\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleByController:Z\n\n    const/4 v1, 0x0\n\n    if-eqz v0, :cond_3\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mBlocked:Z\n\n    if-nez v0, :cond_3\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isStatusBarLocation:Z\n\n    if-nez v0, :cond_0\n\n    invoke-direct {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->isVisibleInCCAndLC()Z\n\n    move-result v0\n\n    if-nez v0, :cond_0\n\n    goto :goto_2\n\n    :cond_0\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    if-eqz v0, :cond_2\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getVisibility()I\n\n    move-result v0\n\n    if-eqz v0, :cond_1\n\n    goto :goto_0\n\n    :cond_1\n    const/4 v0, 0x2\n\n    iput v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mVisibleState:I\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateNetworkSpeed()V\n\n    invoke-virtual {p0, v1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setRemove(Z)V\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->requestLayout()V\n\n    goto :goto_1\n\n    :cond_2\n    :goto_0\n    invoke-virtual {p0, v1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setRemove(Z)V\n\n    invoke-virtual {p0, v1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setVisibility(I)V\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->updateNetworkSpeed()V\n\n    :goto_1\n    return-void\n\n    :cond_3\n    :goto_2\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->getVisibility()I\n\n    move-result v0\n\n    const/16 v2, 0x8\n\n    if-eq v0, v2, :cond_5\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->mHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    iget-boolean v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->animateEnable:Z\n\n    if-nez v0, :cond_4\n\n    goto :goto_3\n\n    :cond_4\n    const/4 v0, 0x1\n\n    invoke-virtual {p0, v0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setRemove(Z)V\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->requestLayout()V\n\n    return-void\n\n    :cond_5\n    :goto_3\n    invoke-virtual {p0, v1}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setRemove(Z)V\n\n    invoke-virtual {p0, v2}, Lcom/android/systemui/statusbar/views/NetworkSpeedView;->setVisibility(I)V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
    {
        'id':             'p0041_field__field_public_isDoub',
        'type':           'field_add',
        'method':         '.field public isDouble:Z',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field public isDouble:Z',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added field',
    },
    {
        'id':             'p0042_field__field_private_isMov',
        'type':           'field_add',
        'method':         '.field private isMove:Z',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field private isMove:Z',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added field',
    },
    {
        'id':             'p0043_field__field_private_isSta',
        'type':           'field_add',
        'method':         '.field private isStatusBarLocation:Z',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field private isStatusBarLocation:Z',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added field',
    },
    {
        'id':             'p0044_field__field_public_mConta',
        'type':           'field_add',
        'method':         '.field public mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field public mContainer:Lcom/android/systemui/newstatusbar/layouts/NetSpeedLayout;',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added field',
    },
    {
        'id':             'p0045_field__field_public_mShown',
        'type':           'field_add',
        'method':         '.field public mShown:Z',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field public mShown:Z',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added field',
    },
    {
        'id':             'p0046_field__field_public_slot_L',
        'type':           'field_add',
        'method':         '.field public slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field public slot:Lcom/android/systemui/newstatusbar/controllers/ElementController$Slots;',
        'required':       False,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr added field',
    },
]
