"""
Legend MiuiSystemUI MTCR patch — modified class.

Target APK   : MiuiSystemUI.apk
Target class : com/miui/charge/view/NumberDrawView.smali
Patches      : 1
"""
from __future__ import annotations

TARGET_APK           = 'MiuiSystemUI.apk'
TARGET_CLASS         = 'com/miui/charge/view/NumberDrawView.smali'
CLASS_FALLBACK_NAMES = ['NumberDrawView.smali']
CLASS_ANCHORS        = ['invoke-direct {p0, p1, v0}, Lcom/miui/charge/view/NumberDrawView;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;)V', 'invoke-direct {p0, p1, p2, v0}, Lcom/miui/charge/view/NumberDrawView;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V', 'invoke-direct {p0, p1, p2, p3}, Landroid/widget/TextView;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V', 'iput-object p2, p0, Lcom/miui/charge/view/NumberDrawView;->mLevel:Ljava/lang/String;', 'iput-object p2, p0, Lcom/miui/charge/view/NumberDrawView;->mShowLevel:Ljava/lang/String;']

PATCHES = [
    {
        'id':             'p0000_setSize',
        'type':           'method_replace',
        'method':         '.method public setSize(III)V',
        'method_name':    'setSize',
        'method_anchors': ['iget-object v0, p0, Lcom/miui/charge/view/NumberDrawView;->mResources:Landroid/content/res/Resources;', 'invoke-virtual {v0}, Landroid/content/res/Resources;->getDisplayMetrics()Landroid/util/DisplayMetrics;', 'invoke-static {v1, p1, v0}, Landroid/util/TypedValue;->applyDimension(IFLandroid/util/DisplayMetrics;)F'],
        'search':         '.method public setSize(III)V\n    .registers 6\n\n    int-to-float p1, p1\n\n    iget-object v0, p0, Lcom/miui/charge/view/NumberDrawView;->mResources:Landroid/content/res/Resources;\n\n    invoke-virtual {v0}, Landroid/content/res/Resources;->getDisplayMetrics()Landroid/util/DisplayMetrics;\n\n    move-result-object v0\n\n    const/4 v1, 0x0\n\n    invoke-static {v1, p1, v0}, Landroid/util/TypedValue;->applyDimension(IFLandroid/util/DisplayMetrics;)F\n\n    move-result p1\n\n    float-to-int p1, p1\n\n    iput p1, p0, Lcom/miui/charge/view/NumberDrawView;->mLargeTextSizePx:I\n\n    int-to-float p1, p2\n\n    iget-object p2, p0, Lcom/miui/charge/view/NumberDrawView;->mResources:Landroid/content/res/Resources;\n\n    invoke-virtual {p2}, Landroid/content/res/Resources;->getDisplayMetrics()Landroid/util/DisplayMetrics;\n\n    move-result-object p2\n\n    invoke-static {v1, p1, p2}, Landroid/util/TypedValue;->applyDimension(IFLandroid/util/DisplayMetrics;)F\n\n    move-result p1\n\n    float-to-int p1, p1\n\n    iput p1, p0, Lcom/miui/charge/view/NumberDrawView;->mSmallTextSizePx:I\n\n    int-to-float p1, p3\n\n    iget-object p2, p0, Lcom/miui/charge/view/NumberDrawView;->mResources:Landroid/content/res/Resources;\n\n    invoke-virtual {p2}, Landroid/content/res/Resources;->getDisplayMetrics()Landroid/util/DisplayMetrics;\n\n    move-result-object p2\n\n    invoke-static {v1, p1, p2}, Landroid/util/TypedValue;->applyDimension(IFLandroid/util/DisplayMetrics;)F\n\n    move-result p1\n\n    float-to-int p1, p1\n\n    iput p1, p0, Lcom/miui/charge/view/NumberDrawView;->mPercentTextSizePx:I\n\n    iget p1, p0, Lcom/miui/charge/view/NumberDrawView;->mLargeTextSizePx:I\n\n    int-to-float p1, p1\n\n    invoke-virtual {p0, v1, p1}, Landroid/widget/TextView;->setTextSize(IF)V\n\n    invoke-virtual {p0}, Lcom/miui/charge/view/NumberDrawView;->updateTextPaint()V\n\n    invoke-virtual {p0}, Landroid/widget/TextView;->requestLayout()V\n\n    return-void\n.end method\n',
        'replacement':    '.method public setSize(III)V\n    .registers 6\n\n    int-to-float p1, p1\n\n    iget-object v0, p0, Lcom/miui/charge/view/NumberDrawView;->mResources:Landroid/content/res/Resources;\n\n    invoke-virtual {v0}, Landroid/content/res/Resources;->getDisplayMetrics()Landroid/util/DisplayMetrics;\n\n    move-result-object v0\n\n    const/4 v1, 0x0\n\n    invoke-static {v1, p1, v0}, Landroid/util/TypedValue;->applyDimension(IFLandroid/util/DisplayMetrics;)F\n\n    move-result p1\n\n    float-to-int p1, p1\n\n    iput p1, p0, Lcom/miui/charge/view/NumberDrawView;->mLargeTextSizePx:I\n\n    int-to-float p1, p2\n\n    iget-object p2, p0, Lcom/miui/charge/view/NumberDrawView;->mResources:Landroid/content/res/Resources;\n\n    invoke-virtual {p2}, Landroid/content/res/Resources;->getDisplayMetrics()Landroid/util/DisplayMetrics;\n\n    move-result-object p2\n\n    invoke-static {v1, p1, p2}, Landroid/util/TypedValue;->applyDimension(IFLandroid/util/DisplayMetrics;)F\n\n    move-result p1\n\n    float-to-int p1, p1\n\n    iput p1, p0, Lcom/miui/charge/view/NumberDrawView;->mSmallTextSizePx:I\n\n    int-to-float p1, p3\n\n    iget-object p2, p0, Lcom/miui/charge/view/NumberDrawView;->mResources:Landroid/content/res/Resources;\n\n    invoke-virtual {p2}, Landroid/content/res/Resources;->getDisplayMetrics()Landroid/util/DisplayMetrics;\n\n    move-result-object p2\n\n    invoke-static {v1, p1, p2}, Landroid/util/TypedValue;->applyDimension(IFLandroid/util/DisplayMetrics;)F\n\n    move-result p1\n\n    float-to-int p1, p1\n\n    iput p1, p0, Lcom/miui/charge/view/NumberDrawView;->mPercentTextSizePx:I\n\n    iget p1, p0, Lcom/miui/charge/view/NumberDrawView;->mLargeTextSizePx:I\n\n    int-to-float p1, p1\n\n    invoke-virtual {p0, v1, p1}, Landroid/widget/TextView;->setTextSize(IF)V\n\n    invoke-virtual {p0}, Lcom/miui/charge/view/NumberDrawView;->updateTextPaint()V\n\n    invoke-virtual {p0}, Lcom/miui/charge/view/NumberDrawView;->doUpdateDrawParams()V\n\n    invoke-virtual {p0}, Landroid/widget/TextView;->requestLayout()V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI MTCR dex.mtcr modified class',
    },
]
