"""
Legend MiuiSystemUI generated patch — modified class.

Target APK   : MiuiSystemUI.apk
Target class : com/miui/systemui/statusbar/views/MobileTypeDrawable.smali
Patches      : 14
"""
from __future__ import annotations

TARGET_APK           = 'MiuiSystemUI.apk'
TARGET_CLASS         = 'com/miui/systemui/statusbar/views/MobileTypeDrawable.smali'
CLASS_FALLBACK_NAMES = ['MobileTypeDrawable.smali']
CLASS_ANCHORS        = ['sget-object v1, Lcom/miui/utils/configs/MiuiConfigs;->FONT_MIPRO_PATH:Ljava/lang/String;', 'invoke-direct {v0, v1}, Landroid/graphics/Typeface$Builder;-><init>(Ljava/lang/String;)V', 'invoke-virtual {v0, v1}, Landroid/graphics/Typeface$Builder;->setFontVariationSettings(Ljava/lang/String;)Landroid/graphics/Typeface$Builder;', 'invoke-virtual {v0}, Landroid/graphics/Typeface$Builder;->build()Landroid/graphics/Typeface;', 'sput-object v0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->sMiproTypeface:Landroid/graphics/Typeface;']

PATCHES = [
    {
        'id':             'p0000__init_',
        'type':           'method_replace',
        'method':         '.method public constructor <init>()V',
        'method_name':    '<init>',
        'method_anchors': ['invoke-direct {p0}, Landroid/graphics/drawable/Drawable;-><init>()V', 'iput-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;', 'iput-boolean v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mShowMobileTypeDoublePlus:Z'],
        'search':         '.method public constructor <init>()V\n    .registers 4\n\n    invoke-direct {p0}, Landroid/graphics/drawable/Drawable;-><init>()V\n\n    const-string v0, ""\n\n    iput-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;\n\n    const/4 v0, 0x0\n\n    iput-boolean v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mShowMobileTypeDoublePlus:Z\n\n    iput-boolean v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mShowSpecial5GIcon:Z\n\n    new-instance v1, Landroid/util/SparseArray;\n\n    invoke-direct {v1}, Landroid/util/SparseArray;-><init>()V\n\n    new-instance v1, Landroid/graphics/Paint;\n\n    invoke-direct {v1}, Landroid/graphics/Paint;-><init>()V\n\n    iput-object v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeTextPaint:Landroid/graphics/Paint;\n\n    new-instance v2, Landroid/graphics/Paint;\n\n    invoke-direct {v2}, Landroid/graphics/Paint;-><init>()V\n\n    iput-object v2, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypePlusPaint:Landroid/graphics/Paint;\n\n    const/4 p0, 0x2\n\n    new-array p0, p0, [Landroid/graphics/Paint;\n\n    aput-object v1, p0, v0\n\n    const/4 v0, 0x1\n\n    aput-object v2, p0, v0\n\n    invoke-static {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->setMiuiStatusBarTypeface([Landroid/graphics/Paint;)V\n\n    return-void\n.end method\n',
        'replacement':    '.method public constructor <init>()V\n    .registers 5\n\n    invoke-direct {p0}, Landroid/graphics/drawable/Drawable;-><init>()V\n\n    const-string v0, ""\n\n    iput-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;\n\n    const/4 v0, 0x0\n\n    iput-boolean v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mShowMobileTypeDoublePlus:Z\n\n    iput-boolean v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mShowSpecial5GIcon:Z\n\n    const-class v1, Lcom/android/systemui/newstatusbar/controllers/MobileIconColorSizeController;\n\n    invoke-static {v1}, Lcom/android/systemui/plugins/ControllerStorage;->get(Ljava/lang/Class;)Ljava/lang/Object;\n\n    move-result-object v1\n\n    check-cast v1, Lcom/android/systemui/newstatusbar/controllers/MobileIconColorSizeController;\n\n    iput-object v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->controller:Lcom/android/systemui/newstatusbar/controllers/MobileIconColorSizeController;\n\n    new-instance v1, Landroid/graphics/Paint;\n\n    invoke-direct {v1}, Landroid/graphics/Paint;-><init>()V\n\n    iput-object v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeTextPaint:Landroid/graphics/Paint;\n\n    new-instance v2, Landroid/graphics/Paint;\n\n    invoke-direct {v2}, Landroid/graphics/Paint;-><init>()V\n\n    iput-object v2, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypePlusPaint:Landroid/graphics/Paint;\n\n    const/4 v3, 0x2\n\n    new-array v3, v3, [Landroid/graphics/Paint;\n\n    aput-object v1, v3, v0\n\n    const/4 v0, 0x1\n\n    aput-object v2, v3, v0\n\n    invoke-static {v3}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->setMiuiStatusBarTypeface([Landroid/graphics/Paint;)V\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI generated generated dex rule modified class',
    },
    {
        'id':             'p0001_getData',
        'type':           'method_add',
        'method':         '.method private getData()Lcom/android/systemui/newstatusbar/data/TextData;',
        'method_name':    'getData',
        'method_anchors': ['iget-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->controller:Lcom/android/systemui/newstatusbar/controllers/MobileIconColorSizeController;', 'invoke-virtual {v0}, Lcom/android/systemui/newstatusbar/controllers/MobileIconColorSizeController;->getSimTypeData()Lcom/android/systemui/newstatusbar/data/TextData;'],
        'search':         None,
        'replacement':    '.method private getData()Lcom/android/systemui/newstatusbar/data/TextData;\n    .registers 2\n\n    iget-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->controller:Lcom/android/systemui/newstatusbar/controllers/MobileIconColorSizeController;\n\n    invoke-virtual {v0}, Lcom/android/systemui/newstatusbar/controllers/MobileIconColorSizeController;->getSimTypeData()Lcom/android/systemui/newstatusbar/data/TextData;\n\n    move-result-object v0\n\n    return-object v0\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0002_setMiuiStatusBarTypeface',
        'type':           'method_replace',
        'method':         '.method public static varargs setMiuiStatusBarTypeface([Landroid/graphics/Paint;)V',
        'method_name':    'setMiuiStatusBarTypeface',
        'method_anchors': ['invoke-static {v0, v1}, Landroid/graphics/Typeface;->create(Ljava/lang/String;I)Landroid/graphics/Typeface;', 'invoke-virtual {v3, v4}, Ljava/lang/Class;->getField(Ljava/lang/String;)Ljava/lang/reflect/Field;', 'invoke-virtual {v3, v4}, Ljava/lang/reflect/Field;->setAccessible(Z)V'],
        'search':         '.method public static varargs setMiuiStatusBarTypeface([Landroid/graphics/Paint;)V\n    .registers 8\n\n    const-string v0, "mipro-bold"\n\n    const/4 v1, 0x0\n\n    invoke-static {v0, v1}, Landroid/graphics/Typeface;->create(Ljava/lang/String;I)Landroid/graphics/Typeface;\n\n    move-result-object v0\n\n    iget-object v2, v0, Landroid/graphics/Typeface;->familyName:[Ljava/lang/String;\n\n    array-length v3, v2\n\n    move v4, v1\n\n    :goto_0\n    if-ge v4, v3, :cond_1\n\n    aget-object v5, v2, v4\n\n    const-string v6, "mipro"\n\n    invoke-virtual {v5, v6}, Ljava/lang/String;->startsWith(Ljava/lang/String;)Z\n\n    move-result v5\n\n    if-eqz v5, :cond_0\n\n    sget-object v0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->sMiproTypeface:Landroid/graphics/Typeface;\n\n    goto :goto_1\n\n    :cond_0\n    add-int/lit8 v4, v4, 0x1\n\n    goto :goto_0\n\n    :cond_1\n    :goto_1\n    array-length v2, p0\n\n    :goto_2\n    if-ge v1, v2, :cond_3\n\n    aget-object v3, p0, v1\n\n    if-eqz v3, :cond_2\n\n    invoke-virtual {v3, v0}, Landroid/graphics/Paint;->setTypeface(Landroid/graphics/Typeface;)Landroid/graphics/Typeface;\n\n    :cond_2\n    add-int/lit8 v1, v1, 0x1\n\n    goto :goto_2\n\n    :cond_3\n    return-void\n.end method\n',
        'replacement':    '.method public static varargs setMiuiStatusBarTypeface([Landroid/graphics/Paint;)V\n    .registers 8\n\n    const-string v0, "mipro-bold"\n\n    const/4 v1, 0x0\n\n    invoke-static {v0, v1}, Landroid/graphics/Typeface;->create(Ljava/lang/String;I)Landroid/graphics/Typeface;\n\n    move-result-object v0\n\n    const/4 v2, 0x0\n\n    :try_start_0\n    const-class v3, Landroid/graphics/Typeface;\n\n    const-string v4, "familyName"\n\n    invoke-virtual {v3, v4}, Ljava/lang/Class;->getField(Ljava/lang/String;)Ljava/lang/reflect/Field;\n\n    move-result-object v3\n\n    const/4 v4, 0x1\n\n    invoke-virtual {v3, v4}, Ljava/lang/reflect/Field;->setAccessible(Z)V\n\n    invoke-virtual {v3, v0}, Ljava/lang/reflect/Field;->get(Ljava/lang/Object;)Ljava/lang/Object;\n\n    move-result-object v4\n\n    check-cast v4, [Ljava/lang/String;\n\n    check-cast v4, [Ljava/lang/String;\n    :try_end_0\n    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0\n\n    move-object v3, v4\n\n    nop\n\n    array-length v4, v3\n\n    const/4 v2, 0x0\n\n    :goto_0\n    if-lt v2, v4, :cond_0\n\n    goto :goto_1\n\n    :cond_0\n    aget-object v5, v3, v2\n\n    const-string v6, "mipro"\n\n    invoke-virtual {v5, v6}, Ljava/lang/String;->startsWith(Ljava/lang/String;)Z\n\n    move-result v5\n\n    if-eqz v5, :cond_3\n\n    sget-object v0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->sMiproTypeface:Landroid/graphics/Typeface;\n\n    nop\n\n    :goto_1\n    array-length v5, p0\n\n    :goto_2\n    if-ge v1, v5, :cond_2\n\n    aget-object v6, p0, v1\n\n    if-eqz v6, :cond_1\n\n    invoke-virtual {v6, v0}, Landroid/graphics/Paint;->setTypeface(Landroid/graphics/Typeface;)Landroid/graphics/Typeface;\n\n    :cond_1\n    add-int/lit8 v1, v1, 0x1\n\n    goto :goto_2\n\n    :cond_2\n    return-void\n\n    :cond_3\n    add-int/lit8 v2, v2, 0x1\n\n    goto :goto_0\n\n    :catch_0\n    move-exception v1\n\n    return-void\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI generated generated dex rule modified class',
    },
    {
        'id':             'p0003_updateMobileTypeLayoutParams',
        'type':           'method_add',
        'method':         '.method public static updateMobileTypeLayoutParams(Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;Ljava/lang/String;Landroid/widget/ImageView;)V',
        'method_name':    'updateMobileTypeLayoutParams',
        'method_anchors': ['invoke-virtual {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->measure()V', 'invoke-virtual {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->getIntrinsicHeight()I', 'invoke-virtual {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->getIntrinsicWidth()I'],
        'search':         None,
        'replacement':    '.method public static updateMobileTypeLayoutParams(Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;Ljava/lang/String;Landroid/widget/ImageView;)V\n    .registers 13\n\n    if-nez p1, :cond_0\n\n    return-void\n\n    :cond_0\n    invoke-virtual {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->measure()V\n\n    invoke-virtual {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->getIntrinsicHeight()I\n\n    move-result v0\n\n    invoke-virtual {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->getIntrinsicWidth()I\n\n    move-result v1\n\n    invoke-virtual {p2}, Landroid/widget/ImageView;->getLayoutParams()Landroid/view/ViewGroup$LayoutParams;\n\n    move-result-object v2\n\n    check-cast v2, Landroid/widget/FrameLayout$LayoutParams;\n\n    iget v3, v2, Landroid/widget/FrameLayout$LayoutParams;->width:I\n\n    if-ne v3, v1, :cond_1\n\n    iget v3, v2, Landroid/widget/FrameLayout$LayoutParams;->height:I\n\n    if-eq v3, v0, :cond_2\n\n    :cond_1\n    iput v1, v2, Landroid/widget/FrameLayout$LayoutParams;->width:I\n\n    iput v0, v2, Landroid/widget/FrameLayout$LayoutParams;->height:I\n\n    invoke-virtual {p2, v2}, Landroid/widget/ImageView;->setLayoutParams(Landroid/view/ViewGroup$LayoutParams;)V\n\n    :cond_2\n    invoke-virtual {p2}, Landroid/widget/ImageView;->getParent()Landroid/view/ViewParent;\n\n    move-result-object v3\n\n    check-cast v3, Lcom/android/systemui/newstatusbar/sim/SimTypeContainer;\n\n    if-eqz v3, :cond_9\n\n    invoke-virtual {v3}, Lcom/android/systemui/newstatusbar/sim/SimTypeContainer;->getInOut()Landroid/view/View;\n\n    move-result-object v4\n\n    invoke-virtual {v3}, Lcom/android/systemui/newstatusbar/sim/SimTypeContainer;->getLayoutParams()Landroid/view/ViewGroup$LayoutParams;\n\n    move-result-object v5\n\n    iget-boolean v6, v3, Lcom/android/systemui/newstatusbar/sim/SimTypeContainer;->isHorizontal:Z\n\n    if-eqz v6, :cond_3\n\n    const/4 v7, 0x1\n\n    goto :goto_0\n\n    :cond_3\n    const/4 v7, 0x2\n\n    :goto_0\n    invoke-virtual {p2}, Landroid/widget/ImageView;->getMeasuredHeight()I\n\n    move-result v8\n\n    mul-int/2addr v7, v8\n\n    const/4 v8, 0x0\n\n    if-eqz v4, :cond_4\n\n    invoke-virtual {v4}, Landroid/view/View;->getMeasuredHeight()I\n\n    move-result v9\n\n    goto :goto_1\n\n    :cond_4\n    move v9, v8\n\n    :goto_1\n    invoke-static {v7, v9}, Ljava/lang/Math;->max(II)I\n\n    move-result v0\n\n    invoke-virtual {p2}, Landroid/widget/ImageView;->getMeasuredWidth()I\n\n    move-result v1\n\n    if-nez v6, :cond_5\n\n    iget-object v7, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeTextPaint:Landroid/graphics/Paint;\n\n    const-string v9, "4G+"\n\n    invoke-virtual {v7, v9}, Landroid/graphics/Paint;->measureText(Ljava/lang/String;)F\n\n    move-result v7\n\n    float-to-int v1, v7\n\n    :cond_5\n    if-eqz v6, :cond_7\n\n    if-eqz v4, :cond_6\n\n    invoke-virtual {v4}, Landroid/view/View;->getMeasuredWidth()I\n\n    move-result v8\n\n    :cond_6\n    add-int/2addr v1, v8\n\n    :cond_7\n    if-nez v6, :cond_8\n\n    mul-int/lit8 v0, v0, 0x2\n\n    :cond_8\n    iput v0, v5, Landroid/view/ViewGroup$LayoutParams;->height:I\n\n    iput v1, v5, Landroid/view/ViewGroup$LayoutParams;->width:I\n\n    invoke-virtual {v3, v5}, Lcom/android/systemui/newstatusbar/sim/SimTypeContainer;->setLayoutParams(Landroid/view/ViewGroup$LayoutParams;)V\n\n    :cond_9\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0004_draw',
        'type':           'method_add',
        'method':         '.method public draw(Landroid/graphics/Canvas;)V',
        'method_name':    'draw',
        'method_anchors': ['iget-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;', 'invoke-static {v0}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z', 'invoke-direct {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->getData()Lcom/android/systemui/newstatusbar/data/TextData;'],
        'search':         None,
        'replacement':    '.method public draw(Landroid/graphics/Canvas;)V\n    .registers 10\n\n    iget-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;\n\n    invoke-static {v0}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z\n\n    move-result v0\n\n    if-eqz v0, :cond_0\n\n    return-void\n\n    :cond_0\n    invoke-direct {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->getData()Lcom/android/systemui/newstatusbar/data/TextData;\n\n    move-result-object v0\n\n    iget-object v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeTextPaint:Landroid/graphics/Paint;\n\n    iget v2, v0, Lcom/android/systemui/newstatusbar/data/TextData;->color:I\n\n    if-nez v2, :cond_1\n\n    iget v2, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeColor:I\n\n    goto :goto_0\n\n    :cond_1\n    invoke-virtual {v0}, Lcom/android/systemui/newstatusbar/data/TextData;->getColor()I\n\n    move-result v2\n\n    :goto_0\n    invoke-virtual {v1, v2}, Landroid/graphics/Paint;->setColor(I)V\n\n    iget v2, v0, Lcom/android/systemui/newstatusbar/data/TextData;->division:I\n\n    int-to-float v2, v2\n\n    const/high16 v3, 0x41200000\n\n    div-float/2addr v2, v3\n\n    invoke-virtual {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->getIntrinsicHeight()I\n\n    move-result v3\n\n    int-to-float v3, v3\n\n    const/high16 v4, 0x40000000\n\n    div-float/2addr v3, v4\n\n    invoke-virtual {v1}, Landroid/graphics/Paint;->descent()F\n\n    move-result v4\n\n    invoke-virtual {v1}, Landroid/graphics/Paint;->ascent()F\n\n    move-result v5\n\n    add-float/2addr v4, v5\n\n    div-float/2addr v4, v2\n\n    sub-float/2addr v3, v4\n\n    iget-object v4, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;\n\n    const/4 v5, 0x0\n\n    invoke-virtual {p1, v4, v5, v3, v1}, Landroid/graphics/Canvas;->drawText(Ljava/lang/String;FFLandroid/graphics/Paint;)V\n\n    iget-boolean v4, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mShowMobileTypeDoublePlus:Z\n\n    if-eqz v4, :cond_2\n\n    iget v4, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mWidth:I\n\n    int-to-float v4, v4\n\n    iget v5, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mHeight:I\n\n    int-to-float v5, v5\n\n    const v6, 0x40266666\n\n    add-float/2addr v5, v6\n\n    iget-object v6, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypePlusPaint:Landroid/graphics/Paint;\n\n    const-string v7, "+"\n\n    invoke-virtual {p1, v7, v4, v5, v6}, Landroid/graphics/Canvas;->drawText(Ljava/lang/String;FFLandroid/graphics/Paint;)V\n\n    iget v4, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mWidth:I\n\n    int-to-float v4, v4\n\n    iget v5, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mHeight:I\n\n    int-to-float v5, v5\n\n    const v6, 0x41066666\n\n    sub-float/2addr v5, v6\n\n    iget-object v6, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypePlusPaint:Landroid/graphics/Paint;\n\n    invoke-virtual {p1, v7, v4, v5, v6}, Landroid/graphics/Canvas;->drawText(Ljava/lang/String;FFLandroid/graphics/Paint;)V\n\n    :cond_2\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0005_getIntrinsicHeight',
        'type':           'method_replace',
        'method':         '.method public final getIntrinsicHeight()I',
        'method_name':    'getIntrinsicHeight',
        'method_anchors': ['iget v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mHeight:I'],
        'search':         '.method public final getIntrinsicHeight()I\n    .registers 1\n\n    iget p0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mHeight:I\n\n    return p0\n.end method\n',
        'replacement':    '.method public final getIntrinsicHeight()I\n    .registers 2\n\n    iget v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mHeight:I\n\n    return v0\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI generated generated dex rule modified class',
    },
    {
        'id':             'p0006_getIntrinsicWidth',
        'type':           'method_replace',
        'method':         '.method public final getIntrinsicWidth()I',
        'method_name':    'getIntrinsicWidth',
        'method_anchors': ['iget v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mWidth:I', 'iget v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mExtraWidth:I'],
        'search':         '.method public final getIntrinsicWidth()I\n    .registers 2\n\n    iget v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mWidth:I\n\n    iget p0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mExtraWidth:I\n\n    add-int/2addr v0, p0\n\n    return v0\n.end method\n',
        'replacement':    '.method public final getIntrinsicWidth()I\n    .registers 3\n\n    iget v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mWidth:I\n\n    iget v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mExtraWidth:I\n\n    add-int/2addr v0, v1\n\n    return v0\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI generated generated dex rule modified class',
    },
    {
        'id':             'p0007_getOpacity',
        'type':           'method_replace',
        'method':         '.method public final getOpacity()I',
        'method_name':    'getOpacity',
        'method_anchors': [],
        'search':         '.method public final getOpacity()I\n    .registers 1\n\n    const/4 p0, -0x3\n\n    return p0\n.end method\n',
        'replacement':    '.method public final getOpacity()I\n    .registers 2\n\n    const/4 v0, -0x3\n\n    return v0\n.end method\n',
        'required':       True,
        'reason':         'Legend MiuiSystemUI generated generated dex rule modified class',
    },
    {
        'id':             'p0008_measure',
        'type':           'method_add',
        'method':         '.method public measure()V',
        'method_name':    'measure',
        'method_anchors': ['iget-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;', 'invoke-static {v0, v1}, Landroid/text/TextUtils;->equals(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Z', 'iput-boolean v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mShowMobileTypeDoublePlus:Z'],
        'search':         None,
        'replacement':    '.method public measure()V\n    .registers 7\n\n    iget-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;\n\n    const-string v1, "5G++"\n\n    invoke-static {v0, v1}, Landroid/text/TextUtils;->equals(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Z\n\n    move-result v0\n\n    const/4 v1, 0x0\n\n    if-eqz v0, :cond_0\n\n    const/4 v0, 0x1\n\n    iput-boolean v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mShowMobileTypeDoublePlus:Z\n\n    const-string v0, "5G"\n\n    iput-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;\n\n    goto :goto_0\n\n    :cond_0\n    iput-boolean v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mShowMobileTypeDoublePlus:Z\n\n    iput v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mExtraWidth:I\n\n    :goto_0\n    invoke-direct {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->getData()Lcom/android/systemui/newstatusbar/data/TextData;\n\n    move-result-object v0\n\n    invoke-virtual {p0, v0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->updateTypefase(Lcom/android/systemui/newstatusbar/data/TextData;)V\n\n    iget v2, v0, Lcom/android/systemui/newstatusbar/data/TextData;->zoom:I\n\n    if-nez v2, :cond_1\n\n    iget v2, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeSize:I\n\n    goto :goto_1\n\n    :cond_1\n    iget v2, v0, Lcom/android/systemui/newstatusbar/data/TextData;->zoom:I\n\n    :goto_1\n    iput v2, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeSize:I\n\n    iget-object v3, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeTextPaint:Landroid/graphics/Paint;\n\n    int-to-float v2, v2\n\n    invoke-virtual {v3, v2}, Landroid/graphics/Paint;->setTextSize(F)V\n\n    iget-object v2, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypePlusPaint:Landroid/graphics/Paint;\n\n    iget v3, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeSize:I\n\n    int-to-float v3, v3\n\n    const v4, 0x3f547ae1\n\n    mul-float/2addr v3, v4\n\n    invoke-virtual {v2, v3}, Landroid/graphics/Paint;->setTextSize(F)V\n\n    iget-object v2, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeTextPaint:Landroid/graphics/Paint;\n\n    iget-object v3, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;\n\n    invoke-virtual {v2, v3}, Landroid/graphics/Paint;->measureText(Ljava/lang/String;)F\n\n    move-result v2\n\n    float-to-double v2, v2\n\n    invoke-static {v2, v3}, Ljava/lang/Math;->ceil(D)D\n\n    move-result-wide v2\n\n    double-to-int v2, v2\n\n    iput v2, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mWidth:I\n\n    iget-object v2, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileType:Ljava/lang/String;\n\n    new-instance v3, Landroid/graphics/Rect;\n\n    invoke-direct {v3}, Landroid/graphics/Rect;-><init>()V\n\n    iget-object v4, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeTextPaint:Landroid/graphics/Paint;\n\n    invoke-virtual {v2}, Ljava/lang/String;->length()I\n\n    move-result v5\n\n    invoke-virtual {v4, v2, v1, v5, v3}, Landroid/graphics/Paint;->getTextBounds(Ljava/lang/String;IILandroid/graphics/Rect;)V\n\n    invoke-virtual {v3}, Landroid/graphics/Rect;->height()I\n\n    move-result v1\n\n    iget v4, v3, Landroid/graphics/Rect;->bottom:I\n\n    add-int/2addr v1, v4\n\n    iput v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mHeight:I\n\n    iget-boolean v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mShowMobileTypeDoublePlus:Z\n\n    if-eqz v1, :cond_2\n\n    iget-object v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypePlusPaint:Landroid/graphics/Paint;\n\n    const-string v4, "+"\n\n    invoke-virtual {v1, v4}, Landroid/graphics/Paint;->measureText(Ljava/lang/String;)F\n\n    move-result v1\n\n    float-to-double v4, v1\n\n    invoke-static {v4, v5}, Ljava/lang/Math;->ceil(D)D\n\n    move-result-wide v4\n\n    double-to-int v1, v4\n\n    iput v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mExtraWidth:I\n\n    :cond_2\n    invoke-virtual {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->invalidateSelf()V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0009_onIconChange',
        'type':           'method_add',
        'method':         '.method public onIconChange()V',
        'method_name':    'onIconChange',
        'method_anchors': ['invoke-virtual {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->measure()V', 'iget-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->parent:Lcom/android/systemui/newstatusbar/sim/MobileTypeImageView;', 'invoke-virtual {v0}, Lcom/android/systemui/newstatusbar/sim/MobileTypeImageView;->updateMobileTypeLayout()V'],
        'search':         None,
        'replacement':    '.method public onIconChange()V\n    .registers 2\n\n    invoke-virtual {p0}, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->measure()V\n\n    iget-object v0, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->parent:Lcom/android/systemui/newstatusbar/sim/MobileTypeImageView;\n\n    invoke-virtual {v0}, Lcom/android/systemui/newstatusbar/sim/MobileTypeImageView;->updateMobileTypeLayout()V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0010_setParent',
        'type':           'method_add',
        'method':         '.method public setParent(Lcom/android/systemui/newstatusbar/sim/MobileTypeImageView;)V',
        'method_name':    'setParent',
        'method_anchors': ['iput-object p1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->parent:Lcom/android/systemui/newstatusbar/sim/MobileTypeImageView;'],
        'search':         None,
        'replacement':    '.method public setParent(Lcom/android/systemui/newstatusbar/sim/MobileTypeImageView;)V\n    .registers 2\n\n    iput-object p1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->parent:Lcom/android/systemui/newstatusbar/sim/MobileTypeImageView;\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0011_updateTypefase',
        'type':           'method_add',
        'method':         '.method public updateTypefase(Lcom/android/systemui/newstatusbar/data/TextData;)V',
        'method_name':    'updateTypefase',
        'method_anchors': ['invoke-virtual {p1}, Lcom/android/systemui/newstatusbar/data/TextData;->getTypeFace()Landroid/graphics/Typeface;', 'iget v1, p1, Lcom/android/systemui/newstatusbar/data/TextData;->typeFaseStyle:I', 'invoke-static {v0, v1}, Landroid/graphics/Typeface;->create(Landroid/graphics/Typeface;I)Landroid/graphics/Typeface;'],
        'search':         None,
        'replacement':    '.method public updateTypefase(Lcom/android/systemui/newstatusbar/data/TextData;)V\n    .registers 4\n\n    invoke-virtual {p1}, Lcom/android/systemui/newstatusbar/data/TextData;->getTypeFace()Landroid/graphics/Typeface;\n\n    move-result-object v0\n\n    iget v1, p1, Lcom/android/systemui/newstatusbar/data/TextData;->typeFaseStyle:I\n\n    invoke-static {v0, v1}, Landroid/graphics/Typeface;->create(Landroid/graphics/Typeface;I)Landroid/graphics/Typeface;\n\n    move-result-object v0\n\n    iget-object v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypeTextPaint:Landroid/graphics/Paint;\n\n    invoke-virtual {v1, v0}, Landroid/graphics/Paint;->setTypeface(Landroid/graphics/Typeface;)Landroid/graphics/Typeface;\n\n    iget-object v1, p0, Lcom/miui/systemui/statusbar/views/MobileTypeDrawable;->mMobileTypePlusPaint:Landroid/graphics/Paint;\n\n    invoke-virtual {v1, v0}, Landroid/graphics/Paint;->setTypeface(Landroid/graphics/Typeface;)Landroid/graphics/Typeface;\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0012_field__field_protected_con',
        'type':           'field_add',
        'method':         '.field protected controller:Lcom/android/systemui/newstatusbar/controllers/MobileIconColorSizeController;',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field protected controller:Lcom/android/systemui/newstatusbar/controllers/MobileIconColorSizeController;',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added field',
    },
    {
        'id':             'p0013_field__field_private_paren',
        'type':           'field_add',
        'method':         '.field private parent:Lcom/android/systemui/newstatusbar/sim/MobileTypeImageView;',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field private parent:Lcom/android/systemui/newstatusbar/sim/MobileTypeImageView;',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added field',
    },
]
