app = "dz-builder-snap"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  SOC = "snapdragon"
  MODE = "dry_run"
  NOTIFY_TELEGRAM = "false"
  DEVICE_CODENAME = "garnet"
  FINAL_NAME = "DeadZone_Test"
  PLATFORM = "os3_a16"
  FLAVOR = "legend"
  ANDROID_VERSION = "16"
  MI_VERSION = "OS3.0.303.0.WNOCNXM"
  VBMETA_MODE = "3"
  KEEP_ALIVE_AFTER_RUN = "true"

[[mounts]]
  source = "deadzone_work"
  destination = "/work"
