"""
Legend MiuiSystemUI generated patch — modified class.

Target APK   : MiuiSystemUI.apk
Target class : com/android/systemui/statusbar/views/MobileSignalAnimatorContainer.smali
Patches      : 20
"""
from __future__ import annotations

TARGET_APK           = 'MiuiSystemUI.apk'
TARGET_CLASS         = 'com/android/systemui/statusbar/views/MobileSignalAnimatorContainer.smali'
CLASS_FALLBACK_NAMES = ['MobileSignalAnimatorContainer.smali']
CLASS_ANCHORS        = ['invoke-direct/range {v0 .. v6}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;IIILkotlin/jvm/internal/DefaultConstructorMarker;)V', 'invoke-direct/range {v0 .. v6}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;IIILkotlin/jvm/internal/DefaultConstructorMarker;)V', 'invoke-direct/range {v0 .. v6}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;IIILkotlin/jvm/internal/DefaultConstructorMarker;)V', 'invoke-direct {p0, p1, p2, p3, p4}, Lcom/android/keyguard/AlphaOptimizedLinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;II)V', 'invoke-direct {p1, p2}, Landroidx/collection/SimpleArrayMap;-><init>(I)V']

PATCHES = [
    {
        'id':             'p0000_getAnimatable',
        'type':           'method_add',
        'method':         '.method public getAnimatable()Lcom/android/systemui/statusbar/views/IAnimatable;',
        'method_name':    'getAnimatable',
        'method_anchors': ['iget-object p0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->animatable:Lcom/android/systemui/statusbar/views/IAnimatable;'],
        'search':         None,
        'replacement':    '.method public getAnimatable()Lcom/android/systemui/statusbar/views/IAnimatable;\n    .registers 1\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->animatable:Lcom/android/systemui/statusbar/views/IAnimatable;\n\n    return-object p0\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0001_getHideByIsland',
        'type':           'method_add',
        'method':         '.method public getHideByIsland()Z',
        'method_name':    'getHideByIsland',
        'method_anchors': ['iget-boolean p0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->hideByIsland:Z'],
        'search':         None,
        'replacement':    '.method public getHideByIsland()Z\n    .registers 1\n\n    iget-boolean p0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->hideByIsland:Z\n\n    return p0\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0002_getIslandController',
        'type':           'method_add',
        'method':         '.method public getIslandController()Lcom/android/systemui/statusbar/StatusBarIslandControllerImpl;',
        'method_name':    'getIslandController',
        'method_anchors': ['iget-object p0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->islandController:Lcom/android/systemui/statusbar/StatusBarIslandControllerImpl;'],
        'search':         None,
        'replacement':    '.method public getIslandController()Lcom/android/systemui/statusbar/StatusBarIslandControllerImpl;\n    .registers 1\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->islandController:Lcom/android/systemui/statusbar/StatusBarIslandControllerImpl;\n\n    return-object p0\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0003_getLastView',
        'type':           'method_add',
        'method':         '.method public getLastView()Landroid/view/View;',
        'method_name':    'getLastView',
        'method_anchors': ['iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->refreshLastView:Z', 'iget-object v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->lastView:Landroid/view/View;', 'invoke-virtual {p0}, Landroid/widget/LinearLayout;->getChildCount()I'],
        'search':         None,
        'replacement':    '.method public getLastView()Landroid/view/View;\n    .registers 4\n\n    iget-boolean v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->refreshLastView:Z\n\n    if-nez v0, :cond_0\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->lastView:Landroid/view/View;\n\n    if-nez v0, :cond_2\n\n    :cond_0\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getChildCount()I\n\n    move-result v0\n\n    add-int/lit8 v0, v0, -0x1\n\n    :goto_0\n    const/4 v1, -0x1\n\n    if-ge v1, v0, :cond_2\n\n    invoke-virtual {p0, v0}, Landroid/widget/LinearLayout;->getChildAt(I)Landroid/view/View;\n\n    move-result-object v1\n\n    invoke-virtual {v1}, Ljava/lang/Object;->getClass()Ljava/lang/Class;\n\n    invoke-virtual {v1}, Landroid/view/View;->getVisibility()I\n\n    move-result v2\n\n    if-nez v2, :cond_1\n\n    invoke-virtual {v1}, Landroid/view/View;->getWidth()I\n\n    move-result v2\n\n    if-eqz v2, :cond_1\n\n    iput-object v1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->lastView:Landroid/view/View;\n\n    goto :goto_1\n\n    :cond_1\n    add-int/lit8 v0, v0, -0x1\n\n    goto :goto_0\n\n    :cond_2\n    :goto_1\n    const/4 v0, 0x0\n\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->refreshLastView:Z\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->lastView:Landroid/view/View;\n\n    return-object p0\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0004_getParentAnimHelper',
        'type':           'method_add',
        'method':         '.method public getParentAnimHelper()Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;',
        'method_name':    'getParentAnimHelper',
        'method_anchors': ['iget-object p0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->parentAnimHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;'],
        'search':         None,
        'replacement':    '.method public getParentAnimHelper()Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n    .registers 1\n\n    iget-object p0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->parentAnimHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    return-object p0\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0005_onChildVisibilityChanged',
        'type':           'method_add',
        'method':         '.method public onChildVisibilityChanged(Landroid/view/View;II)V',
        'method_name':    'onChildVisibilityChanged',
        'method_anchors': ['invoke-super {p0, p1, p2, p3}, Landroid/widget/LinearLayout;->onChildVisibilityChanged(Landroid/view/View;II)V', 'iput-boolean p1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->refreshLastView:Z'],
        'search':         None,
        'replacement':    '.method public onChildVisibilityChanged(Landroid/view/View;II)V\n    .registers 4\n\n    invoke-super {p0, p1, p2, p3}, Landroid/widget/LinearLayout;->onChildVisibilityChanged(Landroid/view/View;II)V\n\n    const/4 p1, 0x1\n\n    iput-boolean p1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->refreshLastView:Z\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0006_onConfigurationChanged',
        'type':           'method_add',
        'method':         '.method public onConfigurationChanged(Landroid/content/res/Configuration;)V',
        'method_name':    'onConfigurationChanged',
        'method_anchors': ['invoke-super {p0, p1}, Landroid/widget/LinearLayout;->onConfigurationChanged(Landroid/content/res/Configuration;)V', 'invoke-virtual {p1}, Landroid/content/res/Configuration;->getLayoutDirection()I', 'iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->isRtl:Z'],
        'search':         None,
        'replacement':    '.method public onConfigurationChanged(Landroid/content/res/Configuration;)V\n    .registers 4\n\n    invoke-super {p0, p1}, Landroid/widget/LinearLayout;->onConfigurationChanged(Landroid/content/res/Configuration;)V\n\n    const/4 v0, 0x0\n\n    if-eqz p1, :cond_0\n\n    invoke-virtual {p1}, Landroid/content/res/Configuration;->getLayoutDirection()I\n\n    move-result p1\n\n    const/4 v1, 0x1\n\n    if-ne p1, v1, :cond_0\n\n    move v0, v1\n\n    :cond_0\n    iput-boolean v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->isRtl:Z\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0007_onDetachedFromWindow',
        'type':           'method_add',
        'method':         '.method public onDetachedFromWindow()V',
        'method_name':    'onDetachedFromWindow',
        'method_anchors': ['invoke-super {p0}, Landroid/widget/LinearLayout;->onDetachedFromWindow()V', 'iput-object v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->animatable:Lcom/android/systemui/statusbar/views/IAnimatable;'],
        'search':         None,
        'replacement':    '.method public onDetachedFromWindow()V\n    .registers 2\n\n    invoke-super {p0}, Landroid/widget/LinearLayout;->onDetachedFromWindow()V\n\n    const/4 v0, 0x0\n\n    iput-object v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->animatable:Lcom/android/systemui/statusbar/views/IAnimatable;\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0008_onFinishInflate',
        'type':           'method_add',
        'method':         '.method public onFinishInflate()V',
        'method_name':    'onFinishInflate',
        'method_anchors': ['invoke-super {p0}, Landroid/widget/LinearLayout;->onFinishInflate()V', 'iget-object v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->layoutChangeListener:Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$layoutChangeListener$1;', 'invoke-virtual {p0, v0}, Landroid/widget/LinearLayout;->addOnLayoutChangeListener(Landroid/view/View$OnLayoutChangeListener;)V'],
        'search':         None,
        'replacement':    '.method public onFinishInflate()V\n    .registers 4\n\n    invoke-super {p0}, Landroid/widget/LinearLayout;->onFinishInflate()V\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->layoutChangeListener:Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$layoutChangeListener$1;\n\n    invoke-virtual {p0, v0}, Landroid/widget/LinearLayout;->addOnLayoutChangeListener(Landroid/view/View$OnLayoutChangeListener;)V\n\n    invoke-virtual {p0}, Landroid/widget/LinearLayout;->getResources()Landroid/content/res/Resources;\n\n    move-result-object v0\n\n    const/4 v1, 0x0\n\n    if-eqz v0, :cond_0\n\n    invoke-virtual {v0}, Landroid/content/res/Resources;->getConfiguration()Landroid/content/res/Configuration;\n\n    move-result-object v0\n\n    if-eqz v0, :cond_0\n\n    invoke-virtual {v0}, Landroid/content/res/Configuration;->getLayoutDirection()I\n\n    move-result v0\n\n    const/4 v2, 0x1\n\n    if-ne v0, v2, :cond_0\n\n    move v1, v2\n\n    :cond_0\n    iput-boolean v1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->isRtl:Z\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0009_onViewAdded',
        'type':           'method_add',
        'method':         '.method public onViewAdded(Landroid/view/View;)V',
        'method_name':    'onViewAdded',
        'method_anchors': ['invoke-super {p0, p1}, Landroid/widget/LinearLayout;->onViewAdded(Landroid/view/View;)V', 'invoke-direct {p0, p1}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;-><init>(Landroid/view/View;)V', 'invoke-virtual {p1, v0, p0}, Landroid/view/View;->setTag(ILjava/lang/Object;)V'],
        'search':         None,
        'replacement':    '.method public onViewAdded(Landroid/view/View;)V\n    .registers 3\n\n    invoke-super {p0, p1}, Landroid/widget/LinearLayout;->onViewAdded(Landroid/view/View;)V\n\n    if-eqz p1, :cond_0\n\n    new-instance p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;\n\n    invoke-direct {p0, p1}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;-><init>(Landroid/view/View;)V\n\n    const v0, 0x7f0b0b75\n\n    invoke-virtual {p1, v0, p0}, Landroid/view/View;->setTag(ILjava/lang/Object;)V\n\n    :cond_0\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0010_onViewRemoved',
        'type':           'method_add',
        'method':         '.method public onViewRemoved(Landroid/view/View;)V',
        'method_name':    'onViewRemoved',
        'method_anchors': ['invoke-super {p0, p1}, Landroid/widget/LinearLayout;->onViewRemoved(Landroid/view/View;)V', 'invoke-virtual {p1, p0, v0}, Landroid/view/View;->setTag(ILjava/lang/Object;)V'],
        'search':         None,
        'replacement':    '.method public onViewRemoved(Landroid/view/View;)V\n    .registers 3\n\n    invoke-super {p0, p1}, Landroid/widget/LinearLayout;->onViewRemoved(Landroid/view/View;)V\n\n    if-eqz p1, :cond_0\n\n    const p0, 0x7f0b0b75\n\n    const/4 v0, 0x0\n\n    invoke-virtual {p1, p0, v0}, Landroid/view/View;->setTag(ILjava/lang/Object;)V\n\n    :cond_0\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0011_setAnimatable',
        'type':           'method_add',
        'method':         '.method public setAnimatable(Lcom/android/systemui/statusbar/views/IAnimatable;)V',
        'method_name':    'setAnimatable',
        'method_anchors': ['iput-object p1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->animatable:Lcom/android/systemui/statusbar/views/IAnimatable;'],
        'search':         None,
        'replacement':    '.method public setAnimatable(Lcom/android/systemui/statusbar/views/IAnimatable;)V\n    .registers 2\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->animatable:Lcom/android/systemui/statusbar/views/IAnimatable;\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0012_setChildVisible',
        'type':           'method_add',
        'method':         '.method public setChildVisible(Landroid/view/View;Z)V',
        'method_name':    'setChildVisible',
        'method_anchors': ['invoke-interface {v0, p2}, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;->setIconVisible(Z)V', 'invoke-interface {v0, v1}, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;->setIslandState(I)V', 'invoke-interface {v0}, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;->getIslandState()I'],
        'search':         None,
        'replacement':    '.method public setChildVisible(Landroid/view/View;Z)V\n    .registers 11\n\n    instance-of v0, p1, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;\n\n    if-eqz v0, :cond_1\n\n    move-object v0, p1\n\n    check-cast v0, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;\n\n    invoke-interface {v0, p2}, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;->setIconVisible(Z)V\n\n    if-nez p2, :cond_0\n\n    const/16 v1, 0x14\n\n    invoke-interface {v0, v1}, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;->setIslandState(I)V\n\n    goto :goto_0\n\n    :cond_0\n    invoke-interface {v0}, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;->getIslandState()I\n\n    move-result v0\n\n    const/16 v1, 0xa\n\n    if-ne v0, v1, :cond_1\n\n    return-void\n\n    :cond_1\n    :goto_0\n    const/4 v0, 0x0\n\n    const/4 v1, 0x0\n\n    const-string v2, "MobileSignalAnimatorContainer"\n\n    const-string v3, " hash ="\n\n    if-eqz p2, :cond_5\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->shouldAnimator()Z\n\n    move-result p2\n\n    iget-object v4, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->fakeViews:Landroidx/collection/ArrayMap;\n\n    invoke-virtual {p1}, Landroid/view/View;->getId()I\n\n    move-result v5\n\n    invoke-static {v5}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;\n\n    move-result-object v5\n\n    invoke-virtual {v4, v5}, Landroidx/collection/SimpleArrayMap;->remove(Ljava/lang/Object;)Ljava/lang/Object;\n\n    move-result-object v4\n\n    check-cast v4, Landroid/view/View;\n\n    if-eqz v4, :cond_2\n\n    invoke-virtual {p0, v4}, Landroid/widget/LinearLayout;->removeTransientView(Landroid/view/View;)V\n\n    invoke-static {v4}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->getViewState(Landroid/view/View;)Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;\n\n    move-result-object p0\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;->cancelAnimator()V\n\n    goto :goto_1\n\n    :cond_2\n    const/4 v4, 0x0\n\n    :goto_1\n    invoke-virtual {p1}, Landroid/view/View;->getVisibility()I\n\n    move-result p0\n\n    if-nez p0, :cond_3\n\n    invoke-virtual {p1}, Landroid/view/View;->getId()I\n\n    move-result p0\n\n    invoke-virtual {p1}, Landroid/view/View;->hashCode()I\n\n    move-result p1\n\n    const-string p2, "appearAnimator: return id = "\n\n    invoke-static {p0, p1, p2, v3, v2}, Landroidx/exifinterface/media/ExifInterface$$ExternalSyntheticOutline0;->m(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V\n\n    return-void\n\n    :cond_3\n    invoke-virtual {p1, v1}, Landroid/view/View;->setVisibility(I)V\n\n    invoke-virtual {p1, v0}, Landroid/view/View;->setTranslationX(F)V\n\n    if-eqz p2, :cond_4\n\n    invoke-static {p1}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->getViewState(Landroid/view/View;)Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;\n\n    move-result-object p0\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;->cancelAnimator()V\n\n    invoke-static {v4, p1}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->copyAnimatorParams(Landroid/view/View;Landroid/view/View;)V\n\n    sget-object p2, Lcom/android/systemui/statusbar/anim/MiuiStatusBarIconAnimatorController;->blurPoint:Ljava/util/ArrayList;\n\n    sget-object p2, Lcom/android/systemui/statusbar/anim/MiuiStatusBarIconAnimatorController$StateTransition;->APPEAR:Lcom/android/systemui/statusbar/anim/MiuiStatusBarIconAnimatorController$StateTransition;\n\n    invoke-static {p2}, Lcom/android/systemui/statusbar/anim/MiuiStatusBarIconAnimatorController$Companion;->getConfig(Lcom/android/systemui/statusbar/anim/MiuiStatusBarIconAnimatorController$StateTransition;)Lmiuix/animation/base/AnimConfig;\n\n    move-result-object p2\n\n    invoke-virtual {p0, v0, p2}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;->animatorAppear(FLmiuix/animation/base/AnimConfig;)V\n\n    goto :goto_2\n\n    :cond_4\n    invoke-static {p1}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->resetViewState$1(Landroid/view/View;)V\n\n    :goto_2\n    invoke-virtual {p1}, Landroid/view/View;->getId()I\n\n    move-result p0\n\n    invoke-virtual {p1}, Landroid/view/View;->hashCode()I\n\n    move-result p1\n\n    const-string p2, "appearAnimator: id = "\n\n    invoke-static {p0, p1, p2, v3, v2}, Landroidx/exifinterface/media/ExifInterface$$ExternalSyntheticOutline0;->m(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V\n\n    return-void\n\n    :cond_5\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->shouldAnimator()Z\n\n    move-result p2\n\n    iget-object v4, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->fakeViews:Landroidx/collection/ArrayMap;\n\n    invoke-virtual {p1}, Landroid/view/View;->getId()I\n\n    move-result v5\n\n    invoke-static {v5}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;\n\n    move-result-object v5\n\n    invoke-virtual {v4, v5}, Landroidx/collection/SimpleArrayMap;->remove(Ljava/lang/Object;)Ljava/lang/Object;\n\n    move-result-object v4\n\n    check-cast v4, Landroid/view/View;\n\n    if-eqz v4, :cond_6\n\n    invoke-virtual {p0, v4}, Landroid/widget/LinearLayout;->removeTransientView(Landroid/view/View;)V\n\n    invoke-static {v4}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->getViewState(Landroid/view/View;)Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;\n\n    move-result-object v4\n\n    invoke-virtual {v4}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;->cancelAnimator()V\n\n    :cond_6\n    invoke-virtual {p1}, Landroid/view/View;->getVisibility()I\n\n    move-result v4\n\n    const/16 v5, 0x8\n\n    if-ne v4, v5, :cond_7\n\n    invoke-virtual {p1}, Landroid/view/View;->getId()I\n\n    move-result p0\n\n    invoke-virtual {p1}, Landroid/view/View;->hashCode()I\n\n    move-result p1\n\n    const-string p2, "disappearAnimator: isVisible false  visible = gone id = "\n\n    const-string v0, " hash = "\n\n    invoke-static {p0, p1, p2, v0, v2}, Landroidx/exifinterface/media/ExifInterface$$ExternalSyntheticOutline0;->m(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V\n\n    return-void\n\n    :cond_7\n    invoke-virtual {p1}, Landroid/view/View;->getVisibility()I\n\n    move-result v4\n\n    const/4 v6, 0x4\n\n    if-ne v4, v6, :cond_8\n\n    invoke-virtual {p1, v5}, Landroid/view/View;->setVisibility(I)V\n\n    invoke-virtual {p1}, Landroid/view/View;->getId()I\n\n    move-result p0\n\n    invoke-virtual {p1}, Landroid/view/View;->hashCode()I\n\n    move-result p1\n\n    const-string p2, "disappearAnimator: isVisible false  visible = invisible id = "\n\n    invoke-static {p0, p1, p2, v3, v2}, Landroidx/exifinterface/media/ExifInterface$$ExternalSyntheticOutline0;->m(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V\n\n    return-void\n\n    :cond_8\n    invoke-virtual {p1}, Landroid/view/View;->getVisibility()I\n\n    move-result v4\n\n    if-nez v4, :cond_9\n\n    if-eqz p2, :cond_9\n\n    invoke-virtual {p1}, Landroid/view/View;->getWidth()I\n\n    move-result p2\n\n    if-eqz p2, :cond_9\n\n    invoke-virtual {p1}, Landroid/view/View;->getHeight()I\n\n    move-result p2\n\n    if-eqz p2, :cond_9\n\n    instance-of p2, p1, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;\n\n    if-eqz p2, :cond_9\n\n    move-object p2, p1\n\n    check-cast p2, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;\n\n    invoke-interface {p2}, Lcom/android/systemui/statusbar/views/MobileSignalDisplayable;->copyView()Landroid/view/View;\n\n    move-result-object p2\n\n    if-eqz p2, :cond_9\n\n    invoke-virtual {p0, p2, v1}, Landroid/widget/LinearLayout;->addTransientView(Landroid/view/View;I)V\n\n    invoke-virtual {p1}, Landroid/view/View;->getLeft()I\n\n    move-result v1\n\n    invoke-virtual {p1}, Landroid/view/View;->getTop()I\n\n    move-result v4\n\n    invoke-virtual {p1}, Landroid/view/View;->getRight()I\n\n    move-result v6\n\n    invoke-virtual {p1}, Landroid/view/View;->getBottom()I\n\n    move-result v7\n\n    invoke-virtual {p2, v1, v4, v6, v7}, Landroid/view/View;->setLeftTopRightBottom(IIII)V\n\n    iget-object v1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->fakeViews:Landroidx/collection/ArrayMap;\n\n    invoke-virtual {p1}, Landroid/view/View;->getId()I\n\n    move-result v4\n\n    invoke-static {v4}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;\n\n    move-result-object v4\n\n    invoke-virtual {v1, v4, p2}, Landroidx/collection/SimpleArrayMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;\n\n    invoke-static {p1, p2}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->copyAnimatorParams(Landroid/view/View;Landroid/view/View;)V\n\n    invoke-static {p2}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->getViewState(Landroid/view/View;)Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;\n\n    move-result-object v1\n\n    const v4, 0x7f0b0b75\n\n    invoke-virtual {p2, v4, v1}, Landroid/view/View;->setTag(ILjava/lang/Object;)V\n\n    sget-object v4, Lcom/android/systemui/statusbar/anim/MiuiStatusBarIconAnimatorController;->blurPoint:Ljava/util/ArrayList;\n\n    sget-object v4, Lcom/android/systemui/statusbar/anim/MiuiStatusBarIconAnimatorController$StateTransition;->DISAPPEAR:Lcom/android/systemui/statusbar/anim/MiuiStatusBarIconAnimatorController$StateTransition;\n\n    invoke-static {v4}, Lcom/android/systemui/statusbar/anim/MiuiStatusBarIconAnimatorController$Companion;->getConfig(Lcom/android/systemui/statusbar/anim/MiuiStatusBarIconAnimatorController$StateTransition;)Lmiuix/animation/base/AnimConfig;\n\n    move-result-object v4\n\n    new-instance v6, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$disappearAnimator$1$1;\n\n    invoke-direct {v6, p0, p2, p1}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$disappearAnimator$1$1;-><init>(Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;Landroid/view/View;Landroid/view/View;)V\n\n    invoke-virtual {v1, v4, v6, v0}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;->animatorDisappear(Lmiuix/animation/base/AnimConfig;Lmiuix/animation/listener/TransitionListener;F)V\n\n    :cond_9\n    invoke-static {p1}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->getViewState(Landroid/view/View;)Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;\n\n    move-result-object p0\n\n    const/4 p2, -0x1\n\n    iput p2, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;->distanceToViewEnd:I\n\n    invoke-virtual {p0}, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$ViewState;->cancelAnimator()V\n\n    invoke-virtual {p1, v5}, Landroid/view/View;->setVisibility(I)V\n\n    invoke-virtual {p1}, Landroid/view/View;->getId()I\n\n    move-result p0\n\n    invoke-virtual {p1}, Landroid/view/View;->hashCode()I\n\n    move-result p1\n\n    const-string p2, "disappearAnimator: id = "\n\n    invoke-static {p0, p1, p2, v3, v2}, Landroidx/exifinterface/media/ExifInterface$$ExternalSyntheticOutline0;->m(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0013_setHideByIsland',
        'type':           'method_add',
        'method':         '.method public setHideByIsland(Z)V',
        'method_name':    'setHideByIsland',
        'method_anchors': ['iput-boolean p1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->hideByIsland:Z'],
        'search':         None,
        'replacement':    '.method public setHideByIsland(Z)V\n    .registers 2\n\n    iput-boolean p1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->hideByIsland:Z\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0014_setIslandController',
        'type':           'method_add',
        'method':         '.method public setIslandController(Lcom/android/systemui/statusbar/StatusBarIslandControllerImpl;)V',
        'method_name':    'setIslandController',
        'method_anchors': ['iput-object p1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->islandController:Lcom/android/systemui/statusbar/StatusBarIslandControllerImpl;'],
        'search':         None,
        'replacement':    '.method public setIslandController(Lcom/android/systemui/statusbar/StatusBarIslandControllerImpl;)V\n    .registers 2\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->islandController:Lcom/android/systemui/statusbar/StatusBarIslandControllerImpl;\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0015_setParentAnimHelper',
        'type':           'method_add',
        'method':         '.method public setParentAnimHelper(Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;)V',
        'method_name':    'setParentAnimHelper',
        'method_anchors': ['iput-object p1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->parentAnimHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;'],
        'search':         None,
        'replacement':    '.method public setParentAnimHelper(Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;)V\n    .registers 2\n\n    iput-object p1, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->parentAnimHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    return-void\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0016_shouldAnimator',
        'type':           'method_add',
        'method':         '.method public shouldAnimator()Z',
        'method_name':    'shouldAnimator',
        'method_anchors': ['iget-object v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->animatable:Lcom/android/systemui/statusbar/views/IAnimatable;', 'invoke-interface {v0}, Lcom/android/systemui/statusbar/views/IAnimatable;->animatorEnable()Z', 'iget-object v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->parentAnimHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;'],
        'search':         None,
        'replacement':    '.method public shouldAnimator()Z\n    .registers 3\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->animatable:Lcom/android/systemui/statusbar/views/IAnimatable;\n\n    if-eqz v0, :cond_0\n\n    invoke-interface {v0}, Lcom/android/systemui/statusbar/views/IAnimatable;->animatorEnable()Z\n\n    move-result v0\n\n    const/4 v1, 0x1\n\n    if-ne v0, v1, :cond_0\n\n    iget-object v0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->parentAnimHelper:Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;\n\n    if-eqz v0, :cond_0\n\n    iget-boolean v0, v0, Lcom/android/systemui/statusbar/anim/StatusBarIconAnimHelper;->removeFlag:Z\n\n    if-nez v0, :cond_0\n\n    iget-boolean p0, p0, Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer;->hideByIsland:Z\n\n    if-nez p0, :cond_0\n\n    return v1\n\n    :cond_0\n    const/4 p0, 0x0\n\n    return p0\n.end method\n',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added method',
    },
    {
        'id':             'p0017_field__field_public_static',
        'type':           'field_add',
        'method':         '.field public static synthetic $r8$clinit:I',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field public static synthetic $r8$clinit:I',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added field',
    },
    {
        'id':             'p0018_field__field_public_fakeVi',
        'type':           'field_add',
        'method':         '.field public fakeViews:Landroidx/collection/ArrayMap;',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field public fakeViews:Landroidx/collection/ArrayMap;',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added field',
    },
    {
        'id':             'p0019_field__field_public_layout',
        'type':           'field_add',
        'method':         '.field public layoutChangeListener:Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$layoutChangeListener$1;',
        'method_name':    '',
        'method_anchors': [],
        'search':         None,
        'replacement':    '.field public layoutChangeListener:Lcom/android/systemui/statusbar/views/MobileSignalAnimatorContainer$layoutChangeListener$1;',
        'required':       False,
        'reason':         'Legend MiuiSystemUI generated generated dex rule added field',
    },
]
