FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git git-lfs ccache python3 python3-pip curl sudo zip unzip rsync \
    build-essential bc libssl-dev lz4 aria2 tzdata \
    gnupg flex bison gperf x11proto-core-dev libx11-dev \
    libxml2-utils xsltproc fontconfig \
    xz-utils brotli zstd file e2fsprogs erofs-utils p7zip-full \
    fuse3

RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo \
    && chmod a+x /usr/local/bin/repo

RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt update && apt install gh -y

COPY build_script.sh /build_script.sh
RUN chmod +x /build_script.sh

ENTRYPOINT ["/build_script.sh"]
